// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::storeTopup
 * @see \D:\Lar\dmpos\app\Http\Controllers\MembershipCard\CustomerCardController.php:149
 * @route "http://127.0.0.1:8000/membership-cards/{membershipCard}/topup"
 */
export const store = (args: { membershipCard: number | { id: number } } | [ membershipCard: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "http://127.0.0.1:8000/membership-cards/{membershipCard}/topup",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::storeTopup
 * @see \D:\Lar\dmpos\app\Http\Controllers\MembershipCard\CustomerCardController.php:149
 * @route "http://127.0.0.1:8000/membership-cards/{membershipCard}/topup"
 */
store.url = (args: { membershipCard: number | { id: number } } | [ membershipCard: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { membershipCard: args }
}
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
    args = { membershipCard: args.id }
}
    
    if (Array.isArray(args)) {
    args = {
        membershipCard: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        membershipCard: typeof args.membershipCard === "object" ? args.membershipCard.id : args.membershipCard,
    }
    
    return store.definition.url
        .replace("{membershipCard}", parsedArgs.membershipCard.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::storeTopup
 * @see \D:\Lar\dmpos\app\Http\Controllers\MembershipCard\CustomerCardController.php:149
 * @route "http://127.0.0.1:8000/membership-cards/{membershipCard}/topup"
 */
store.post = (args: { membershipCard: number | { id: number } } | [ membershipCard: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::storeTopup
 * @see \D:\Lar\dmpos\app\Http\Controllers\MembershipCard\CustomerCardController.php:149
 * @route "http://127.0.0.1:8000/membership-cards/{membershipCard}/topup"
 */
const storeForm = (args: { membershipCard: number | { id: number } } | [ membershipCard: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(args, options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::storeTopup
 * @see \D:\Lar\dmpos\app\Http\Controllers\MembershipCard\CustomerCardController.php:149
 * @route "http://127.0.0.1:8000/membership-cards/{membershipCard}/topup"
 */
storeForm.post = (args: { membershipCard: number | { id: number } } | [ membershipCard: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(args, options),
    method: "post",
})



store.form = storeForm

const topup = {
    store,
}

export default topup