// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../index';
import permissions from './permissions';
import roles from './roles';

/**
 * @see \App\Http\Controllers\Users\UserController::__invoke
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Users/UserController.php:16
 * @route "http://localhost/users"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

index.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/users',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\Users\UserController::__invoke
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Users/UserController.php:16
 * @route "http://localhost/users"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\Users\UserController::__invoke
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Users/UserController.php:16
 * @route "http://localhost/users"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Users\UserController::__invoke
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Users/UserController.php:16
 * @route "http://localhost/users"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: index.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\Users\UserController::__invoke
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Users/UserController.php:16
 * @route "http://localhost/users"
 */
const indexForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Users\UserController::__invoke
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Users/UserController.php:16
 * @route "http://localhost/users"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Users\UserController::__invoke
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Users/UserController.php:16
 * @route "http://localhost/users"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(formSafeOptions('head', options)),
    method: 'get',
});

index.form = indexForm;

const users = {
    index,
    roles,
    permissions,
};

export default users;
