// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \App\Http\Controllers\Feature\HttpController::useHttpApi
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\HttpController.php:17
 * @route "http://127.0.0.1:8000/features/http/use-http/api"
 */
export const api = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: api.url(options),
    method: "post",
})

api.definition = {
    methods: ["post"],
    url: "http://127.0.0.1:8000/features/http/use-http/api",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\Feature\HttpController::useHttpApi
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\HttpController.php:17
 * @route "http://127.0.0.1:8000/features/http/use-http/api"
 */
api.url = (options?: RouteQueryOptions) => {
    return api.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Feature\HttpController::useHttpApi
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\HttpController.php:17
 * @route "http://127.0.0.1:8000/features/http/use-http/api"
 */
api.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: api.url(options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\Feature\HttpController::useHttpApi
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\HttpController.php:17
 * @route "http://127.0.0.1:8000/features/http/use-http/api"
 */
const apiForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: api.url(options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\Feature\HttpController::useHttpApi
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\HttpController.php:17
 * @route "http://127.0.0.1:8000/features/http/use-http/api"
 */
apiForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: api.url(options),
    method: "post",
})



api.form = apiForm

const useHttp = {
    api,
}

export default useHttp