// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    applyUrlDefaults,
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../index';

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:22
 * @route "http://localhost/purchase"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

index.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/purchase',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:22
 * @route "http://localhost/purchase"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:22
 * @route "http://localhost/purchase"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:22
 * @route "http://localhost/purchase"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: index.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:22
 * @route "http://localhost/purchase"
 */
const indexForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:22
 * @route "http://localhost/purchase"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:22
 * @route "http://localhost/purchase"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(formSafeOptions('head', options)),
    method: 'get',
});

index.form = indexForm;
/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:101
 * @route "http://localhost/purchase"
 */
export const store = (
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: store.url(options),
    method: 'post',
});

store.definition = {
    methods: ['post'],
    url: 'http://localhost/purchase',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:101
 * @route "http://localhost/purchase"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:101
 * @route "http://localhost/purchase"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<'post'> => ({
    url: store.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:101
 * @route "http://localhost/purchase"
 */
const storeForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:101
 * @route "http://localhost/purchase"
 */
storeForm.post = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(options),
    method: 'post',
});

store.form = storeForm;
/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::update
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:275
 * @route "http://localhost/purchase/{purchaseOrder}"
 */
export const update = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: update.url(args, options),
    method: 'patch',
});

update.definition = {
    methods: ['patch'],
    url: 'http://localhost/purchase/{purchaseOrder}',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::update
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:275
 * @route "http://localhost/purchase/{purchaseOrder}"
 */
update.url = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { purchaseOrder: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { purchaseOrder: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            purchaseOrder: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        purchaseOrder:
            typeof args.purchaseOrder === 'object'
                ? args.purchaseOrder.id
                : args.purchaseOrder,
    };

    return (
        update.definition.url
            .replace('{purchaseOrder}', parsedArgs.purchaseOrder.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::update
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:275
 * @route "http://localhost/purchase/{purchaseOrder}"
 */
update.patch = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: update.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::update
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:275
 * @route "http://localhost/purchase/{purchaseOrder}"
 */
const updateForm = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: update.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::update
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:275
 * @route "http://localhost/purchase/{purchaseOrder}"
 */
updateForm.patch = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: update.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

update.form = updateForm;
/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:173
 * @route "http://localhost/purchase/{purchaseOrder}/approve"
 */
export const approve = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: approve.url(args, options),
    method: 'patch',
});

approve.definition = {
    methods: ['patch'],
    url: 'http://localhost/purchase/{purchaseOrder}/approve',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:173
 * @route "http://localhost/purchase/{purchaseOrder}/approve"
 */
approve.url = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { purchaseOrder: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { purchaseOrder: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            purchaseOrder: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        purchaseOrder:
            typeof args.purchaseOrder === 'object'
                ? args.purchaseOrder.id
                : args.purchaseOrder,
    };

    return (
        approve.definition.url
            .replace('{purchaseOrder}', parsedArgs.purchaseOrder.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:173
 * @route "http://localhost/purchase/{purchaseOrder}/approve"
 */
approve.patch = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: approve.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:173
 * @route "http://localhost/purchase/{purchaseOrder}/approve"
 */
const approveForm = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: approve.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:173
 * @route "http://localhost/purchase/{purchaseOrder}/approve"
 */
approveForm.patch = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: approve.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

approve.form = approveForm;
/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:186
 * @route "http://localhost/purchase/{purchaseOrder}/reject"
 */
export const reject = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: reject.url(args, options),
    method: 'patch',
});

reject.definition = {
    methods: ['patch'],
    url: 'http://localhost/purchase/{purchaseOrder}/reject',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:186
 * @route "http://localhost/purchase/{purchaseOrder}/reject"
 */
reject.url = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { purchaseOrder: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { purchaseOrder: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            purchaseOrder: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        purchaseOrder:
            typeof args.purchaseOrder === 'object'
                ? args.purchaseOrder.id
                : args.purchaseOrder,
    };

    return (
        reject.definition.url
            .replace('{purchaseOrder}', parsedArgs.purchaseOrder.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:186
 * @route "http://localhost/purchase/{purchaseOrder}/reject"
 */
reject.patch = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: reject.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:186
 * @route "http://localhost/purchase/{purchaseOrder}/reject"
 */
const rejectForm = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: reject.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:186
 * @route "http://localhost/purchase/{purchaseOrder}/reject"
 */
rejectForm.patch = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: reject.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

reject.form = rejectForm;
/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:199
 * @route "http://localhost/purchase/{purchaseOrder}/cancel"
 */
export const cancel = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: cancel.url(args, options),
    method: 'patch',
});

cancel.definition = {
    methods: ['patch'],
    url: 'http://localhost/purchase/{purchaseOrder}/cancel',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:199
 * @route "http://localhost/purchase/{purchaseOrder}/cancel"
 */
cancel.url = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { purchaseOrder: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { purchaseOrder: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            purchaseOrder: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        purchaseOrder:
            typeof args.purchaseOrder === 'object'
                ? args.purchaseOrder.id
                : args.purchaseOrder,
    };

    return (
        cancel.definition.url
            .replace('{purchaseOrder}', parsedArgs.purchaseOrder.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:199
 * @route "http://localhost/purchase/{purchaseOrder}/cancel"
 */
cancel.patch = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: cancel.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:199
 * @route "http://localhost/purchase/{purchaseOrder}/cancel"
 */
const cancelForm = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: cancel.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Purchase\PurchaseOrderController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Purchase/PurchaseOrderController.php:199
 * @route "http://localhost/purchase/{purchaseOrder}/cancel"
 */
cancelForm.patch = (
    args:
        | { purchaseOrder: number | { id: number } }
        | [purchaseOrder: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: cancel.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

cancel.form = cancelForm;

const purchase = {
    index,
    store,
    update,
    approve,
    reject,
    cancel,
};

export default purchase;
