// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    applyUrlDefaults,
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../../index';

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::previewCurrentInvoice
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:516
 * @route "http://localhost/orders/{diningSession}/print/current-invoice"
 */
export const preview = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: preview.url(args, options),
    method: 'get',
});

preview.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/orders/{diningSession}/print/current-invoice',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::previewCurrentInvoice
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:516
 * @route "http://localhost/orders/{diningSession}/print/current-invoice"
 */
preview.url = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { diningSession: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { diningSession: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            diningSession: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        diningSession:
            typeof args.diningSession === 'object'
                ? args.diningSession.id
                : args.diningSession,
    };

    return (
        preview.definition.url
            .replace('{diningSession}', parsedArgs.diningSession.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::previewCurrentInvoice
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:516
 * @route "http://localhost/orders/{diningSession}/print/current-invoice"
 */
preview.get = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: preview.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::previewCurrentInvoice
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:516
 * @route "http://localhost/orders/{diningSession}/print/current-invoice"
 */
preview.head = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'head'> => ({
    url: preview.url(args, options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::previewCurrentInvoice
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:516
 * @route "http://localhost/orders/{diningSession}/print/current-invoice"
 */
const previewForm = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: preview.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::previewCurrentInvoice
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:516
 * @route "http://localhost/orders/{diningSession}/print/current-invoice"
 */
previewForm.get = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: preview.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::previewCurrentInvoice
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:516
 * @route "http://localhost/orders/{diningSession}/print/current-invoice"
 */
previewForm.head = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: preview.url(args, formSafeOptions('head', options)),
    method: 'get',
});

preview.form = previewForm;

const currentInvoice = {
    preview,
};

export default currentInvoice;
