// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    applyUrlDefaults,
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../../index';

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:16
 * @route "http://localhost/access-control/printers"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

index.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/access-control/printers',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:16
 * @route "http://localhost/access-control/printers"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:16
 * @route "http://localhost/access-control/printers"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:16
 * @route "http://localhost/access-control/printers"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: index.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:16
 * @route "http://localhost/access-control/printers"
 */
const indexForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:16
 * @route "http://localhost/access-control/printers"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:16
 * @route "http://localhost/access-control/printers"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(formSafeOptions('head', options)),
    method: 'get',
});

index.form = indexForm;
/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:121
 * @route "http://localhost/access-control/printers"
 */
export const store = (
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: store.url(options),
    method: 'post',
});

store.definition = {
    methods: ['post'],
    url: 'http://localhost/access-control/printers',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:121
 * @route "http://localhost/access-control/printers"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:121
 * @route "http://localhost/access-control/printers"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<'post'> => ({
    url: store.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:121
 * @route "http://localhost/access-control/printers"
 */
const storeForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:121
 * @route "http://localhost/access-control/printers"
 */
storeForm.post = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(options),
    method: 'post',
});

store.form = storeForm;
/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::update
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:145
 * @route "http://localhost/access-control/printers/{printer}"
 */
export const update = (
    args:
        | { printer: number | { id: number } }
        | [printer: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: update.url(args, options),
    method: 'patch',
});

update.definition = {
    methods: ['patch'],
    url: 'http://localhost/access-control/printers/{printer}',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::update
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:145
 * @route "http://localhost/access-control/printers/{printer}"
 */
update.url = (
    args:
        | { printer: number | { id: number } }
        | [printer: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { printer: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { printer: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            printer: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        printer:
            typeof args.printer === 'object' ? args.printer.id : args.printer,
    };

    return (
        update.definition.url
            .replace('{printer}', parsedArgs.printer.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::update
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:145
 * @route "http://localhost/access-control/printers/{printer}"
 */
update.patch = (
    args:
        | { printer: number | { id: number } }
        | [printer: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: update.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::update
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:145
 * @route "http://localhost/access-control/printers/{printer}"
 */
const updateForm = (
    args:
        | { printer: number | { id: number } }
        | [printer: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: update.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::update
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:145
 * @route "http://localhost/access-control/printers/{printer}"
 */
updateForm.patch = (
    args:
        | { printer: number | { id: number } }
        | [printer: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: update.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

update.form = updateForm;
/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::logs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:66
 * @route "http://localhost/access-control/printer-logs"
 */
export const logs = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: logs.url(options),
    method: 'get',
});

logs.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/access-control/printer-logs',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::logs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:66
 * @route "http://localhost/access-control/printer-logs"
 */
logs.url = (options?: RouteQueryOptions) => {
    return logs.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::logs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:66
 * @route "http://localhost/access-control/printer-logs"
 */
logs.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: logs.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::logs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:66
 * @route "http://localhost/access-control/printer-logs"
 */
logs.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: logs.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::logs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:66
 * @route "http://localhost/access-control/printer-logs"
 */
const logsForm = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: logs.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::logs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:66
 * @route "http://localhost/access-control/printer-logs"
 */
logsForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: logs.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::logs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:66
 * @route "http://localhost/access-control/printer-logs"
 */
logsForm.head = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: logs.url(formSafeOptions('head', options)),
    method: 'get',
});

logs.form = logsForm;
/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::destroyLogs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:102
 * @route "http://localhost/access-control/printer-logs"
 */
export const destroyLogs = (
    options?: RouteQueryOptions,
): RouteDefinition<'delete'> => ({
    url: destroyLogs.url(options),
    method: 'delete',
});

destroyLogs.definition = {
    methods: ['delete'],
    url: 'http://localhost/access-control/printer-logs',
} satisfies RouteDefinition<['delete']>;

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::destroyLogs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:102
 * @route "http://localhost/access-control/printer-logs"
 */
destroyLogs.url = (options?: RouteQueryOptions) => {
    return destroyLogs.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::destroyLogs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:102
 * @route "http://localhost/access-control/printer-logs"
 */
destroyLogs.delete = (
    options?: RouteQueryOptions,
): RouteDefinition<'delete'> => ({
    url: destroyLogs.url(options),
    method: 'delete',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::destroyLogs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:102
 * @route "http://localhost/access-control/printer-logs"
 */
const destroyLogsForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: destroyLogs.url(formSafeOptions('delete', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::destroyLogs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:102
 * @route "http://localhost/access-control/printer-logs"
 */
destroyLogsForm.delete = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: destroyLogs.url(formSafeOptions('delete', options)),
    method: 'post',
});

destroyLogs.form = destroyLogsForm;

const PrinterController = {
    index,
    store,
    update,
    logs,
    destroyLogs,
};

export default PrinterController;
