// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:15
 * @route "http://127.0.0.1:8000/master-data/customers"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "http://127.0.0.1:8000/master-data/customers",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:15
 * @route "http://127.0.0.1:8000/master-data/customers"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:15
 * @route "http://127.0.0.1:8000/master-data/customers"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:15
 * @route "http://127.0.0.1:8000/master-data/customers"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\MasterData\CustomerController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:15
 * @route "http://127.0.0.1:8000/master-data/customers"
 */
const indexForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:15
 * @route "http://127.0.0.1:8000/master-data/customers"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:15
 * @route "http://127.0.0.1:8000/master-data/customers"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(formSafeOptions("head", options)),
    method: "get",
})



index.form = indexForm
/**
 * @see \App\Http\Controllers\MasterData\CustomerController::storeMembershipCard
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:81
 * @route "http://127.0.0.1:8000/master-data/customers/{customer}/membership-cards"
 */
export const storeMembershipCard = (args: { customer: number | { id: number } } | [ customer: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: storeMembershipCard.url(args, options),
    method: "post",
})

storeMembershipCard.definition = {
    methods: ["post"],
    url: "http://127.0.0.1:8000/master-data/customers/{customer}/membership-cards",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::storeMembershipCard
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:81
 * @route "http://127.0.0.1:8000/master-data/customers/{customer}/membership-cards"
 */
storeMembershipCard.url = (args: { customer: number | { id: number } } | [ customer: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { customer: args }
}
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
    args = { customer: args.id }
}
    
    if (Array.isArray(args)) {
    args = {
        customer: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        customer: typeof args.customer === "object" ? args.customer.id : args.customer,
    }
    
    return storeMembershipCard.definition.url
        .replace("{customer}", parsedArgs.customer.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::storeMembershipCard
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:81
 * @route "http://127.0.0.1:8000/master-data/customers/{customer}/membership-cards"
 */
storeMembershipCard.post = (args: { customer: number | { id: number } } | [ customer: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: storeMembershipCard.url(args, options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\MasterData\CustomerController::storeMembershipCard
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:81
 * @route "http://127.0.0.1:8000/master-data/customers/{customer}/membership-cards"
 */
const storeMembershipCardForm = (args: { customer: number | { id: number } } | [ customer: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: storeMembershipCard.url(args, options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::storeMembershipCard
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:81
 * @route "http://127.0.0.1:8000/master-data/customers/{customer}/membership-cards"
 */
storeMembershipCardForm.post = (args: { customer: number | { id: number } } | [ customer: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: storeMembershipCard.url(args, options),
    method: "post",
})



storeMembershipCard.form = storeMembershipCardForm
/**
 * @see \App\Http\Controllers\MasterData\CustomerController::updateMembershipCard
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:106
 * @route "http://127.0.0.1:8000/master-data/customers/{customer}/membership-cards/{membershipCard}"
 */
export const updateMembershipCard = (args: { customer: number | { id: number }, membershipCard: number | { id: number } } | [ customer: number | { id: number }, membershipCard: number | { id: number } ], options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: updateMembershipCard.url(args, options),
    method: "patch",
})

updateMembershipCard.definition = {
    methods: ["patch"],
    url: "http://127.0.0.1:8000/master-data/customers/{customer}/membership-cards/{membershipCard}",
} satisfies RouteDefinition<["patch"]>

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::updateMembershipCard
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:106
 * @route "http://127.0.0.1:8000/master-data/customers/{customer}/membership-cards/{membershipCard}"
 */
updateMembershipCard.url = (args: { customer: number | { id: number }, membershipCard: number | { id: number } } | [ customer: number | { id: number }, membershipCard: number | { id: number } ], options?: RouteQueryOptions) => {
    if (Array.isArray(args)) {
    args = {
        customer: args[0],
        membershipCard: args[1],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        customer: typeof args.customer === "object" ? args.customer.id : args.customer,
        membershipCard: typeof args.membershipCard === "object" ? args.membershipCard.id : args.membershipCard,
    }
    
    return updateMembershipCard.definition.url
        .replace("{customer}", parsedArgs.customer.toString())
        .replace("{membershipCard}", parsedArgs.membershipCard.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::updateMembershipCard
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:106
 * @route "http://127.0.0.1:8000/master-data/customers/{customer}/membership-cards/{membershipCard}"
 */
updateMembershipCard.patch = (args: { customer: number | { id: number }, membershipCard: number | { id: number } } | [ customer: number | { id: number }, membershipCard: number | { id: number } ], options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: updateMembershipCard.url(args, options),
    method: "patch",
})



/**
 * @see \App\Http\Controllers\MasterData\CustomerController::updateMembershipCard
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:106
 * @route "http://127.0.0.1:8000/master-data/customers/{customer}/membership-cards/{membershipCard}"
 */
const updateMembershipCardForm = (args: { customer: number | { id: number }, membershipCard: number | { id: number } } | [ customer: number | { id: number }, membershipCard: number | { id: number } ], options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: updateMembershipCard.url(args, formSafeOptions("patch", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::updateMembershipCard
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:106
 * @route "http://127.0.0.1:8000/master-data/customers/{customer}/membership-cards/{membershipCard}"
 */
updateMembershipCardForm.patch = (args: { customer: number | { id: number }, membershipCard: number | { id: number } } | [ customer: number | { id: number }, membershipCard: number | { id: number } ], options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: updateMembershipCard.url(args, formSafeOptions("patch", options)),
    method: "post",
})



updateMembershipCard.form = updateMembershipCardForm

const CustomerController = {
    index,
    storeMembershipCard,
    updateMembershipCard,
}

export default CustomerController