// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../../index';

/**
 * @see \App\Http\Controllers\MasterData\ProductController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:21
 * @route "http://localhost/master-data/products"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

index.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/master-data/products',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\MasterData\ProductController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:21
 * @route "http://localhost/master-data/products"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\MasterData\ProductController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:21
 * @route "http://localhost/master-data/products"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MasterData\ProductController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:21
 * @route "http://localhost/master-data/products"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: index.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\MasterData\ProductController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:21
 * @route "http://localhost/master-data/products"
 */
const indexForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MasterData\ProductController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:21
 * @route "http://localhost/master-data/products"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MasterData\ProductController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:21
 * @route "http://localhost/master-data/products"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(formSafeOptions('head', options)),
    method: 'get',
});

index.form = indexForm;
/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:81
 * @route "http://localhost/master-data/products/items"
 */
export const storeItem = (
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: storeItem.url(options),
    method: 'post',
});

storeItem.definition = {
    methods: ['post'],
    url: 'http://localhost/master-data/products/items',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:81
 * @route "http://localhost/master-data/products/items"
 */
storeItem.url = (options?: RouteQueryOptions) => {
    return storeItem.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:81
 * @route "http://localhost/master-data/products/items"
 */
storeItem.post = (options?: RouteQueryOptions): RouteDefinition<'post'> => ({
    url: storeItem.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:81
 * @route "http://localhost/master-data/products/items"
 */
const storeItemForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: storeItem.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:81
 * @route "http://localhost/master-data/products/items"
 */
storeItemForm.post = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: storeItem.url(options),
    method: 'post',
});

storeItem.form = storeItemForm;
/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeBom
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:117
 * @route "http://localhost/master-data/products/bom"
 */
export const storeBom = (
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: storeBom.url(options),
    method: 'post',
});

storeBom.definition = {
    methods: ['post'],
    url: 'http://localhost/master-data/products/bom',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeBom
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:117
 * @route "http://localhost/master-data/products/bom"
 */
storeBom.url = (options?: RouteQueryOptions) => {
    return storeBom.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeBom
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:117
 * @route "http://localhost/master-data/products/bom"
 */
storeBom.post = (options?: RouteQueryOptions): RouteDefinition<'post'> => ({
    url: storeBom.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeBom
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:117
 * @route "http://localhost/master-data/products/bom"
 */
const storeBomForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: storeBom.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeBom
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:117
 * @route "http://localhost/master-data/products/bom"
 */
storeBomForm.post = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: storeBom.url(options),
    method: 'post',
});

storeBom.form = storeBomForm;

const ProductController = {
    index,
    storeItem,
    storeBom,
};

export default ProductController;
