// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../../index';

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:12
 * @route "http://localhost/master-data/suppliers"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

index.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/master-data/suppliers',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:12
 * @route "http://localhost/master-data/suppliers"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:12
 * @route "http://localhost/master-data/suppliers"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:12
 * @route "http://localhost/master-data/suppliers"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: index.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:12
 * @route "http://localhost/master-data/suppliers"
 */
const indexForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:12
 * @route "http://localhost/master-data/suppliers"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:12
 * @route "http://localhost/master-data/suppliers"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(formSafeOptions('head', options)),
    method: 'get',
});

index.form = indexForm;

const SupplierController = {
    index,
};

export default SupplierController;
