// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    applyUrlDefaults,
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../../index';

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:65
 * @route "http://localhost/master-data/suppliers"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

index.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/master-data/suppliers',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:65
 * @route "http://localhost/master-data/suppliers"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:65
 * @route "http://localhost/master-data/suppliers"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:65
 * @route "http://localhost/master-data/suppliers"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: index.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:65
 * @route "http://localhost/master-data/suppliers"
 */
const indexForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:65
 * @route "http://localhost/master-data/suppliers"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:65
 * @route "http://localhost/master-data/suppliers"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(formSafeOptions('head', options)),
    method: 'get',
});

index.form = indexForm;
/**
 * @see \App\Http\Controllers\MasterData\SupplierController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:13
 * @route "http://localhost/master-data/suppliers"
 */
export const store = (
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: store.url(options),
    method: 'post',
});

store.definition = {
    methods: ['post'],
    url: 'http://localhost/master-data/suppliers',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:13
 * @route "http://localhost/master-data/suppliers"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:13
 * @route "http://localhost/master-data/suppliers"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<'post'> => ({
    url: store.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:13
 * @route "http://localhost/master-data/suppliers"
 */
const storeForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:13
 * @route "http://localhost/master-data/suppliers"
 */
storeForm.post = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(options),
    method: 'post',
});

store.form = storeForm;
/**
 * @see \App\Http\Controllers\MasterData\SupplierController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:41
 * @route "http://localhost/master-data/suppliers/{supplier}/approve"
 */
export const approve = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: approve.url(args, options),
    method: 'patch',
});

approve.definition = {
    methods: ['patch'],
    url: 'http://localhost/master-data/suppliers/{supplier}/approve',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:41
 * @route "http://localhost/master-data/suppliers/{supplier}/approve"
 */
approve.url = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { supplier: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { supplier: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            supplier: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        supplier:
            typeof args.supplier === 'object'
                ? args.supplier.id
                : args.supplier,
    };

    return (
        approve.definition.url
            .replace('{supplier}', parsedArgs.supplier.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:41
 * @route "http://localhost/master-data/suppliers/{supplier}/approve"
 */
approve.patch = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: approve.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:41
 * @route "http://localhost/master-data/suppliers/{supplier}/approve"
 */
const approveForm = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: approve.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:41
 * @route "http://localhost/master-data/suppliers/{supplier}/approve"
 */
approveForm.patch = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: approve.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

approve.form = approveForm;
/**
 * @see \App\Http\Controllers\MasterData\SupplierController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:49
 * @route "http://localhost/master-data/suppliers/{supplier}/reject"
 */
export const reject = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: reject.url(args, options),
    method: 'patch',
});

reject.definition = {
    methods: ['patch'],
    url: 'http://localhost/master-data/suppliers/{supplier}/reject',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:49
 * @route "http://localhost/master-data/suppliers/{supplier}/reject"
 */
reject.url = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { supplier: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { supplier: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            supplier: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        supplier:
            typeof args.supplier === 'object'
                ? args.supplier.id
                : args.supplier,
    };

    return (
        reject.definition.url
            .replace('{supplier}', parsedArgs.supplier.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:49
 * @route "http://localhost/master-data/suppliers/{supplier}/reject"
 */
reject.patch = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: reject.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:49
 * @route "http://localhost/master-data/suppliers/{supplier}/reject"
 */
const rejectForm = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: reject.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:49
 * @route "http://localhost/master-data/suppliers/{supplier}/reject"
 */
rejectForm.patch = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: reject.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

reject.form = rejectForm;
/**
 * @see \App\Http\Controllers\MasterData\SupplierController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:57
 * @route "http://localhost/master-data/suppliers/{supplier}/cancel"
 */
export const cancel = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: cancel.url(args, options),
    method: 'patch',
});

cancel.definition = {
    methods: ['patch'],
    url: 'http://localhost/master-data/suppliers/{supplier}/cancel',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:57
 * @route "http://localhost/master-data/suppliers/{supplier}/cancel"
 */
cancel.url = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { supplier: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { supplier: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            supplier: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        supplier:
            typeof args.supplier === 'object'
                ? args.supplier.id
                : args.supplier,
    };

    return (
        cancel.definition.url
            .replace('{supplier}', parsedArgs.supplier.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:57
 * @route "http://localhost/master-data/suppliers/{supplier}/cancel"
 */
cancel.patch = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: cancel.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:57
 * @route "http://localhost/master-data/suppliers/{supplier}/cancel"
 */
const cancelForm = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: cancel.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/SupplierController.php:57
 * @route "http://localhost/master-data/suppliers/{supplier}/cancel"
 */
cancelForm.patch = (
    args:
        | { supplier: number | { id: number } }
        | [supplier: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: cancel.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

cancel.form = cancelForm;

const SupplierController = {
    index,
    store,
    approve,
    reject,
    cancel,
};

export default SupplierController;
