// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \App\Http\Controllers\MasterData\WarehouseLocationController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\WarehouseLocationController.php:13
 * @route "http://localhost:8000/master-data/warehouse-locations"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/master-data/warehouse-locations",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\MasterData\WarehouseLocationController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\WarehouseLocationController.php:13
 * @route "http://localhost:8000/master-data/warehouse-locations"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\WarehouseLocationController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\WarehouseLocationController.php:13
 * @route "http://localhost:8000/master-data/warehouse-locations"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\WarehouseLocationController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\WarehouseLocationController.php:13
 * @route "http://localhost:8000/master-data/warehouse-locations"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\MasterData\WarehouseLocationController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\WarehouseLocationController.php:13
 * @route "http://localhost:8000/master-data/warehouse-locations"
 */
const indexForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\WarehouseLocationController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\WarehouseLocationController.php:13
 * @route "http://localhost:8000/master-data/warehouse-locations"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\WarehouseLocationController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\WarehouseLocationController.php:13
 * @route "http://localhost:8000/master-data/warehouse-locations"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(formSafeOptions("head", options)),
    method: "get",
})



index.form = indexForm

const WarehouseLocationController = {
    index,
}

export default WarehouseLocationController