// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import SeatController from './SeatController';
import SeatOrderController from './SeatOrderController';

export const Seats = {
    SeatOrderController,
    SeatController,
};

export default Seats;
