// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import PutawayController from './PutawayController';

export const Putaway = {
    PutawayController,
};

export default Putaway;
