// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import branches from "./branches";

export const company-branches = {
    branches,
}

export default company-branches