// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../../index';

/**
 * @see \App\Http\Controllers\Crm\DashboardController::__invoke
 * @see \D:\Lar\dmpos\app\Http\Controllers\Crm\DashboardController.php:14
 * @route "/dashboard"
 */
const DashboardController = (
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: DashboardController.url(options),
    method: 'get',
});

DashboardController.definition = {
    methods: ['get', 'head'],
    url: '/dashboard',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\Crm\DashboardController::__invoke
 * @see \D:\Lar\dmpos\app\Http\Controllers\Crm\DashboardController.php:14
 * @route "/dashboard"
 */
DashboardController.url = (options?: RouteQueryOptions) => {
    return DashboardController.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\Crm\DashboardController::__invoke
 * @see \D:\Lar\dmpos\app\Http\Controllers\Crm\DashboardController.php:14
 * @route "/dashboard"
 */
DashboardController.get = (
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: DashboardController.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Crm\DashboardController::__invoke
 * @see \D:\Lar\dmpos\app\Http\Controllers\Crm\DashboardController.php:14
 * @route "/dashboard"
 */
DashboardController.head = (
    options?: RouteQueryOptions,
): RouteDefinition<'head'> => ({
    url: DashboardController.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\Crm\DashboardController::__invoke
 * @see \D:\Lar\dmpos\app\Http\Controllers\Crm\DashboardController.php:14
 * @route "/dashboard"
 */
const DashboardControllerForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: DashboardController.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Crm\DashboardController::__invoke
 * @see \D:\Lar\dmpos\app\Http\Controllers\Crm\DashboardController.php:14
 * @route "/dashboard"
 */
DashboardControllerForm.get = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: DashboardController.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Crm\DashboardController::__invoke
 * @see \D:\Lar\dmpos\app\Http\Controllers\Crm\DashboardController.php:14
 * @route "/dashboard"
 */
DashboardControllerForm.head = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: DashboardController.url(formSafeOptions('head', options)),
    method: 'get',
});

DashboardController.form = DashboardControllerForm;

export default DashboardController;
