// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \App\Http\Controllers\Crm\NoteController::store
 * @see \D:\Lar\dmpos\app\Http\Controllers\Crm\NoteController.php:12
 * @route "http://localhost:8000/contacts/{contact}/notes"
 */
export const store = (args: { contact: number | { id: number } } | [ contact: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "http://localhost:8000/contacts/{contact}/notes",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\Crm\NoteController::store
 * @see \D:\Lar\dmpos\app\Http\Controllers\Crm\NoteController.php:12
 * @route "http://localhost:8000/contacts/{contact}/notes"
 */
store.url = (args: { contact: number | { id: number } } | [ contact: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { contact: args }
}
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
    args = { contact: args.id }
}
    
    if (Array.isArray(args)) {
    args = {
        contact: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        contact: typeof args.contact === "object" ? args.contact.id : args.contact,
    }
    
    return store.definition.url
        .replace("{contact}", parsedArgs.contact.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Crm\NoteController::store
 * @see \D:\Lar\dmpos\app\Http\Controllers\Crm\NoteController.php:12
 * @route "http://localhost:8000/contacts/{contact}/notes"
 */
store.post = (args: { contact: number | { id: number } } | [ contact: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\Crm\NoteController::store
 * @see \D:\Lar\dmpos\app\Http\Controllers\Crm\NoteController.php:12
 * @route "http://localhost:8000/contacts/{contact}/notes"
 */
const storeForm = (args: { contact: number | { id: number } } | [ contact: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(args, options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\Crm\NoteController::store
 * @see \D:\Lar\dmpos\app\Http\Controllers\Crm\NoteController.php:12
 * @route "http://localhost:8000/contacts/{contact}/notes"
 */
storeForm.post = (args: { contact: number | { id: number } } | [ contact: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(args, options),
    method: "post",
})



store.form = storeForm

const NoteController = {
    store,
}

export default NoteController