// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import bom from './bom';
import items from './items';

export const products = {
    items,
    bom,
};

export default products;
