// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    applyUrlDefaults,
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../../index';

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:18
 * @route "http://localhost/membership-cards"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

index.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/membership-cards',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:18
 * @route "http://localhost/membership-cards"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:18
 * @route "http://localhost/membership-cards"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:18
 * @route "http://localhost/membership-cards"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: index.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:18
 * @route "http://localhost/membership-cards"
 */
const indexForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:18
 * @route "http://localhost/membership-cards"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:18
 * @route "http://localhost/membership-cards"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(formSafeOptions('head', options)),
    method: 'get',
});

index.form = indexForm;
/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:44
 * @route "http://localhost/membership-cards/create"
 */
export const create = (
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: create.url(options),
    method: 'get',
});

create.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/membership-cards/create',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:44
 * @route "http://localhost/membership-cards/create"
 */
create.url = (options?: RouteQueryOptions) => {
    return create.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:44
 * @route "http://localhost/membership-cards/create"
 */
create.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: create.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:44
 * @route "http://localhost/membership-cards/create"
 */
create.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: create.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:44
 * @route "http://localhost/membership-cards/create"
 */
const createForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: create.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:44
 * @route "http://localhost/membership-cards/create"
 */
createForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: create.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:44
 * @route "http://localhost/membership-cards/create"
 */
createForm.head = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: create.url(formSafeOptions('head', options)),
    method: 'get',
});

create.form = createForm;
/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:73
 * @route "http://localhost/membership-cards"
 */
export const store = (
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: store.url(options),
    method: 'post',
});

store.definition = {
    methods: ['post'],
    url: 'http://localhost/membership-cards',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:73
 * @route "http://localhost/membership-cards"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:73
 * @route "http://localhost/membership-cards"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<'post'> => ({
    url: store.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:73
 * @route "http://localhost/membership-cards"
 */
const storeForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:73
 * @route "http://localhost/membership-cards"
 */
storeForm.post = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(options),
    method: 'post',
});

store.form = storeForm;
/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::transactions
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:119
 * @route "http://localhost/membership-cards/{membershipCard}/transactions"
 */
export const transactions = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: transactions.url(args, options),
    method: 'get',
});

transactions.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/membership-cards/{membershipCard}/transactions',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::transactions
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:119
 * @route "http://localhost/membership-cards/{membershipCard}/transactions"
 */
transactions.url = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { membershipCard: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { membershipCard: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            membershipCard: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        membershipCard:
            typeof args.membershipCard === 'object'
                ? args.membershipCard.id
                : args.membershipCard,
    };

    return (
        transactions.definition.url
            .replace('{membershipCard}', parsedArgs.membershipCard.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::transactions
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:119
 * @route "http://localhost/membership-cards/{membershipCard}/transactions"
 */
transactions.get = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: transactions.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::transactions
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:119
 * @route "http://localhost/membership-cards/{membershipCard}/transactions"
 */
transactions.head = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteDefinition<'head'> => ({
    url: transactions.url(args, options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::transactions
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:119
 * @route "http://localhost/membership-cards/{membershipCard}/transactions"
 */
const transactionsForm = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: transactions.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::transactions
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:119
 * @route "http://localhost/membership-cards/{membershipCard}/transactions"
 */
transactionsForm.get = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: transactions.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::transactions
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:119
 * @route "http://localhost/membership-cards/{membershipCard}/transactions"
 */
transactionsForm.head = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: transactions.url(args, formSafeOptions('head', options)),
    method: 'get',
});

transactions.form = transactionsForm;
/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::topup
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:138
 * @route "http://localhost/membership-cards/{membershipCard}/topup"
 */
export const topup = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: topup.url(args, options),
    method: 'get',
});

topup.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/membership-cards/{membershipCard}/topup',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::topup
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:138
 * @route "http://localhost/membership-cards/{membershipCard}/topup"
 */
topup.url = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { membershipCard: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { membershipCard: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            membershipCard: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        membershipCard:
            typeof args.membershipCard === 'object'
                ? args.membershipCard.id
                : args.membershipCard,
    };

    return (
        topup.definition.url
            .replace('{membershipCard}', parsedArgs.membershipCard.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::topup
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:138
 * @route "http://localhost/membership-cards/{membershipCard}/topup"
 */
topup.get = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: topup.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::topup
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:138
 * @route "http://localhost/membership-cards/{membershipCard}/topup"
 */
topup.head = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteDefinition<'head'> => ({
    url: topup.url(args, options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::topup
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:138
 * @route "http://localhost/membership-cards/{membershipCard}/topup"
 */
const topupForm = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: topup.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::topup
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:138
 * @route "http://localhost/membership-cards/{membershipCard}/topup"
 */
topupForm.get = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: topup.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::topup
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:138
 * @route "http://localhost/membership-cards/{membershipCard}/topup"
 */
topupForm.head = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: topup.url(args, formSafeOptions('head', options)),
    method: 'get',
});

topup.form = topupForm;
/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::storeTopup
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:149
 * @route "http://localhost/membership-cards/{membershipCard}/topup"
 */
export const storeTopup = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: storeTopup.url(args, options),
    method: 'post',
});

storeTopup.definition = {
    methods: ['post'],
    url: 'http://localhost/membership-cards/{membershipCard}/topup',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::storeTopup
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:149
 * @route "http://localhost/membership-cards/{membershipCard}/topup"
 */
storeTopup.url = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { membershipCard: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { membershipCard: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            membershipCard: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        membershipCard:
            typeof args.membershipCard === 'object'
                ? args.membershipCard.id
                : args.membershipCard,
    };

    return (
        storeTopup.definition.url
            .replace('{membershipCard}', parsedArgs.membershipCard.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::storeTopup
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:149
 * @route "http://localhost/membership-cards/{membershipCard}/topup"
 */
storeTopup.post = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: storeTopup.url(args, options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::storeTopup
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:149
 * @route "http://localhost/membership-cards/{membershipCard}/topup"
 */
const storeTopupForm = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: storeTopup.url(args, options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MembershipCard\CustomerCardController::storeTopup
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MembershipCard/CustomerCardController.php:149
 * @route "http://localhost/membership-cards/{membershipCard}/topup"
 */
storeTopupForm.post = (
    args:
        | { membershipCard: number | null | { id: number | null } }
        | [membershipCard: number | null | { id: number | null }]
        | number
        | null
        | { id: number | null },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: storeTopup.url(args, options),
    method: 'post',
});

storeTopup.form = storeTopupForm;

const CustomerCardController = {
    index,
    create,
    store,
    transactions,
    topup,
    storeTopup,
};

export default CustomerCardController;
