// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    applyUrlDefaults,
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../../index';

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::storeMembershipCard
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/CustomerController.php:81
 * @route "http://localhost/master-data/customers/{customer}/membership-cards"
 */
export const store = (
    args:
        | { customer: number | { id: number } }
        | [customer: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: store.url(args, options),
    method: 'post',
});

store.definition = {
    methods: ['post'],
    url: 'http://localhost/master-data/customers/{customer}/membership-cards',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::storeMembershipCard
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/CustomerController.php:81
 * @route "http://localhost/master-data/customers/{customer}/membership-cards"
 */
store.url = (
    args:
        | { customer: number | { id: number } }
        | [customer: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { customer: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { customer: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            customer: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        customer:
            typeof args.customer === 'object'
                ? args.customer.id
                : args.customer,
    };

    return (
        store.definition.url
            .replace('{customer}', parsedArgs.customer.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::storeMembershipCard
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/CustomerController.php:81
 * @route "http://localhost/master-data/customers/{customer}/membership-cards"
 */
store.post = (
    args:
        | { customer: number | { id: number } }
        | [customer: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: store.url(args, options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::storeMembershipCard
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/CustomerController.php:81
 * @route "http://localhost/master-data/customers/{customer}/membership-cards"
 */
const storeForm = (
    args:
        | { customer: number | { id: number } }
        | [customer: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(args, options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::storeMembershipCard
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/CustomerController.php:81
 * @route "http://localhost/master-data/customers/{customer}/membership-cards"
 */
storeForm.post = (
    args:
        | { customer: number | { id: number } }
        | [customer: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(args, options),
    method: 'post',
});

store.form = storeForm;
/**
 * @see \App\Http\Controllers\MasterData\CustomerController::updateMembershipCard
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/CustomerController.php:106
 * @route "http://localhost/master-data/customers/{customer}/membership-cards/{membershipCard}"
 */
export const update = (
    args:
        | {
              customer: number | { id: number };
              membershipCard: number | null | { id: number | null };
          }
        | [
              customer: number | { id: number },
              membershipCard: number | null | { id: number | null },
          ],
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: update.url(args, options),
    method: 'patch',
});

update.definition = {
    methods: ['patch'],
    url: 'http://localhost/master-data/customers/{customer}/membership-cards/{membershipCard}',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::updateMembershipCard
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/CustomerController.php:106
 * @route "http://localhost/master-data/customers/{customer}/membership-cards/{membershipCard}"
 */
update.url = (
    args:
        | {
              customer: number | { id: number };
              membershipCard: number | null | { id: number | null };
          }
        | [
              customer: number | { id: number },
              membershipCard: number | null | { id: number | null },
          ],
    options?: RouteQueryOptions,
) => {
    if (Array.isArray(args)) {
        args = {
            customer: args[0],
            membershipCard: args[1],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        customer:
            typeof args.customer === 'object'
                ? args.customer.id
                : args.customer,
        membershipCard:
            typeof args.membershipCard === 'object'
                ? args.membershipCard.id
                : args.membershipCard,
    };

    return (
        update.definition.url
            .replace('{customer}', parsedArgs.customer.toString())
            .replace('{membershipCard}', parsedArgs.membershipCard.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::updateMembershipCard
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/CustomerController.php:106
 * @route "http://localhost/master-data/customers/{customer}/membership-cards/{membershipCard}"
 */
update.patch = (
    args:
        | {
              customer: number | { id: number };
              membershipCard: number | null | { id: number | null };
          }
        | [
              customer: number | { id: number },
              membershipCard: number | null | { id: number | null },
          ],
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: update.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::updateMembershipCard
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/CustomerController.php:106
 * @route "http://localhost/master-data/customers/{customer}/membership-cards/{membershipCard}"
 */
const updateForm = (
    args:
        | {
              customer: number | { id: number };
              membershipCard: number | null | { id: number | null };
          }
        | [
              customer: number | { id: number },
              membershipCard: number | null | { id: number | null },
          ],
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: update.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::updateMembershipCard
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/CustomerController.php:106
 * @route "http://localhost/master-data/customers/{customer}/membership-cards/{membershipCard}"
 */
updateForm.patch = (
    args:
        | {
              customer: number | { id: number };
              membershipCard: number | null | { id: number | null };
          }
        | [
              customer: number | { id: number },
              membershipCard: number | null | { id: number | null },
          ],
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: update.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

update.form = updateForm;

const membershipCards = {
    store,
    update,
};

export default membershipCards;
