// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../index';
import globalEvents5439f0d from './global-events';
import progressFb9fab3 from './progress';
import visitCallbacks0d0e0f9 from './visit-callbacks';

/**
 * @see \App\Http\Controllers\Feature\EventController::globalEvents
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:12
 * @route "http://localhost/features/events/global-events"
 */
export const globalEvents = (
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: globalEvents.url(options),
    method: 'get',
});

globalEvents.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/features/events/global-events',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\Feature\EventController::globalEvents
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:12
 * @route "http://localhost/features/events/global-events"
 */
globalEvents.url = (options?: RouteQueryOptions) => {
    return globalEvents.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\Feature\EventController::globalEvents
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:12
 * @route "http://localhost/features/events/global-events"
 */
globalEvents.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: globalEvents.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Feature\EventController::globalEvents
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:12
 * @route "http://localhost/features/events/global-events"
 */
globalEvents.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: globalEvents.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\Feature\EventController::globalEvents
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:12
 * @route "http://localhost/features/events/global-events"
 */
const globalEventsForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: globalEvents.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Feature\EventController::globalEvents
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:12
 * @route "http://localhost/features/events/global-events"
 */
globalEventsForm.get = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: globalEvents.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Feature\EventController::globalEvents
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:12
 * @route "http://localhost/features/events/global-events"
 */
globalEventsForm.head = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: globalEvents.url(formSafeOptions('head', options)),
    method: 'get',
});

globalEvents.form = globalEventsForm;
/**
 * @see \App\Http\Controllers\Feature\EventController::visitCallbacks
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:22
 * @route "http://localhost/features/events/visit-callbacks"
 */
export const visitCallbacks = (
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: visitCallbacks.url(options),
    method: 'get',
});

visitCallbacks.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/features/events/visit-callbacks',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\Feature\EventController::visitCallbacks
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:22
 * @route "http://localhost/features/events/visit-callbacks"
 */
visitCallbacks.url = (options?: RouteQueryOptions) => {
    return visitCallbacks.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\Feature\EventController::visitCallbacks
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:22
 * @route "http://localhost/features/events/visit-callbacks"
 */
visitCallbacks.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: visitCallbacks.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Feature\EventController::visitCallbacks
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:22
 * @route "http://localhost/features/events/visit-callbacks"
 */
visitCallbacks.head = (
    options?: RouteQueryOptions,
): RouteDefinition<'head'> => ({
    url: visitCallbacks.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\Feature\EventController::visitCallbacks
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:22
 * @route "http://localhost/features/events/visit-callbacks"
 */
const visitCallbacksForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: visitCallbacks.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Feature\EventController::visitCallbacks
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:22
 * @route "http://localhost/features/events/visit-callbacks"
 */
visitCallbacksForm.get = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: visitCallbacks.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Feature\EventController::visitCallbacks
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:22
 * @route "http://localhost/features/events/visit-callbacks"
 */
visitCallbacksForm.head = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: visitCallbacks.url(formSafeOptions('head', options)),
    method: 'get',
});

visitCallbacks.form = visitCallbacksForm;
/**
 * @see \App\Http\Controllers\Feature\EventController::progress
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:32
 * @route "http://localhost/features/events/progress"
 */
export const progress = (
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: progress.url(options),
    method: 'get',
});

progress.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/features/events/progress',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\Feature\EventController::progress
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:32
 * @route "http://localhost/features/events/progress"
 */
progress.url = (options?: RouteQueryOptions) => {
    return progress.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\Feature\EventController::progress
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:32
 * @route "http://localhost/features/events/progress"
 */
progress.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: progress.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Feature\EventController::progress
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:32
 * @route "http://localhost/features/events/progress"
 */
progress.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: progress.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\Feature\EventController::progress
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:32
 * @route "http://localhost/features/events/progress"
 */
const progressForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: progress.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Feature\EventController::progress
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:32
 * @route "http://localhost/features/events/progress"
 */
progressForm.get = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: progress.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Feature\EventController::progress
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:32
 * @route "http://localhost/features/events/progress"
 */
progressForm.head = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: progress.url(formSafeOptions('head', options)),
    method: 'get',
});

progress.form = progressForm;

const events = {
    'global-events': globalEvents,
    'visit-callbacks': visitCallbacks,
    globalEvents: Object.assign(globalEvents, globalEvents5439f0d),
    visitCallbacks: Object.assign(visitCallbacks, visitCallbacks0d0e0f9),
    progress: Object.assign(progress, progressFb9fab3),
};

export default events;
