// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \App\Http\Controllers\MasterData\MenuController::storeCategory
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuController.php:213
 * @route "http://localhost:8000/master-data/menu/categories"
 */
export const store = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "http://localhost:8000/master-data/menu/categories",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\MasterData\MenuController::storeCategory
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuController.php:213
 * @route "http://localhost:8000/master-data/menu/categories"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\MenuController::storeCategory
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuController.php:213
 * @route "http://localhost:8000/master-data/menu/categories"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\MasterData\MenuController::storeCategory
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuController.php:213
 * @route "http://localhost:8000/master-data/menu/categories"
 */
const storeForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\MasterData\MenuController::storeCategory
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuController.php:213
 * @route "http://localhost:8000/master-data/menu/categories"
 */
storeForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(options),
    method: "post",
})



store.form = storeForm

const categories = {
    store,
}

export default categories