// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\Users\UserController::storeRole
 * @see \D:\Lar\dmpos\app\Http\Controllers\Users\UserController.php:93
 * @route "http://127.0.0.1:8000/users/roles"
 */
export const store = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "http://127.0.0.1:8000/users/roles",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\Users\UserController::storeRole
 * @see \D:\Lar\dmpos\app\Http\Controllers\Users\UserController.php:93
 * @route "http://127.0.0.1:8000/users/roles"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Users\UserController::storeRole
 * @see \D:\Lar\dmpos\app\Http\Controllers\Users\UserController.php:93
 * @route "http://127.0.0.1:8000/users/roles"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\Users\UserController::storeRole
 * @see \D:\Lar\dmpos\app\Http\Controllers\Users\UserController.php:93
 * @route "http://127.0.0.1:8000/users/roles"
 */
const storeForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\Users\UserController::storeRole
 * @see \D:\Lar\dmpos\app\Http\Controllers\Users\UserController.php:93
 * @route "http://127.0.0.1:8000/users/roles"
 */
storeForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(options),
    method: "post",
})



store.form = storeForm

const roles = {
    store,
}

export default roles