// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    applyUrlDefaults,
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../../index';

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:23
 * @route "http://localhost/goods-receipts"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

index.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/goods-receipts',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:23
 * @route "http://localhost/goods-receipts"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:23
 * @route "http://localhost/goods-receipts"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:23
 * @route "http://localhost/goods-receipts"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: index.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:23
 * @route "http://localhost/goods-receipts"
 */
const indexForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:23
 * @route "http://localhost/goods-receipts"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:23
 * @route "http://localhost/goods-receipts"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(formSafeOptions('head', options)),
    method: 'get',
});

index.form = indexForm;
/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:48
 * @route "http://localhost/goods-receipts/create"
 */
export const create = (
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: create.url(options),
    method: 'get',
});

create.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/goods-receipts/create',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:48
 * @route "http://localhost/goods-receipts/create"
 */
create.url = (options?: RouteQueryOptions) => {
    return create.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:48
 * @route "http://localhost/goods-receipts/create"
 */
create.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: create.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:48
 * @route "http://localhost/goods-receipts/create"
 */
create.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: create.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:48
 * @route "http://localhost/goods-receipts/create"
 */
const createForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: create.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:48
 * @route "http://localhost/goods-receipts/create"
 */
createForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: create.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:48
 * @route "http://localhost/goods-receipts/create"
 */
createForm.head = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: create.url(formSafeOptions('head', options)),
    method: 'get',
});

create.form = createForm;
/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:67
 * @route "http://localhost/goods-receipts"
 */
export const store = (
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: store.url(options),
    method: 'post',
});

store.definition = {
    methods: ['post'],
    url: 'http://localhost/goods-receipts',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:67
 * @route "http://localhost/goods-receipts"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:67
 * @route "http://localhost/goods-receipts"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<'post'> => ({
    url: store.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:67
 * @route "http://localhost/goods-receipts"
 */
const storeForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:67
 * @route "http://localhost/goods-receipts"
 */
storeForm.post = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(options),
    method: 'post',
});

store.form = storeForm;
/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:180
 * @route "http://localhost/goods-receipts/{goodsReceipt}/approve"
 */
export const approve = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: approve.url(args, options),
    method: 'patch',
});

approve.definition = {
    methods: ['patch'],
    url: 'http://localhost/goods-receipts/{goodsReceipt}/approve',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:180
 * @route "http://localhost/goods-receipts/{goodsReceipt}/approve"
 */
approve.url = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { goodsReceipt: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { goodsReceipt: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            goodsReceipt: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        goodsReceipt:
            typeof args.goodsReceipt === 'object'
                ? args.goodsReceipt.id
                : args.goodsReceipt,
    };

    return (
        approve.definition.url
            .replace('{goodsReceipt}', parsedArgs.goodsReceipt.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:180
 * @route "http://localhost/goods-receipts/{goodsReceipt}/approve"
 */
approve.patch = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: approve.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:180
 * @route "http://localhost/goods-receipts/{goodsReceipt}/approve"
 */
const approveForm = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: approve.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:180
 * @route "http://localhost/goods-receipts/{goodsReceipt}/approve"
 */
approveForm.patch = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: approve.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

approve.form = approveForm;
/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:247
 * @route "http://localhost/goods-receipts/{goodsReceipt}/reject"
 */
export const reject = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: reject.url(args, options),
    method: 'patch',
});

reject.definition = {
    methods: ['patch'],
    url: 'http://localhost/goods-receipts/{goodsReceipt}/reject',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:247
 * @route "http://localhost/goods-receipts/{goodsReceipt}/reject"
 */
reject.url = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { goodsReceipt: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { goodsReceipt: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            goodsReceipt: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        goodsReceipt:
            typeof args.goodsReceipt === 'object'
                ? args.goodsReceipt.id
                : args.goodsReceipt,
    };

    return (
        reject.definition.url
            .replace('{goodsReceipt}', parsedArgs.goodsReceipt.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:247
 * @route "http://localhost/goods-receipts/{goodsReceipt}/reject"
 */
reject.patch = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: reject.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:247
 * @route "http://localhost/goods-receipts/{goodsReceipt}/reject"
 */
const rejectForm = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: reject.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:247
 * @route "http://localhost/goods-receipts/{goodsReceipt}/reject"
 */
rejectForm.patch = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: reject.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

reject.form = rejectForm;
/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:256
 * @route "http://localhost/goods-receipts/{goodsReceipt}/cancel"
 */
export const cancel = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: cancel.url(args, options),
    method: 'patch',
});

cancel.definition = {
    methods: ['patch'],
    url: 'http://localhost/goods-receipts/{goodsReceipt}/cancel',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:256
 * @route "http://localhost/goods-receipts/{goodsReceipt}/cancel"
 */
cancel.url = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { goodsReceipt: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { goodsReceipt: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            goodsReceipt: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        goodsReceipt:
            typeof args.goodsReceipt === 'object'
                ? args.goodsReceipt.id
                : args.goodsReceipt,
    };

    return (
        cancel.definition.url
            .replace('{goodsReceipt}', parsedArgs.goodsReceipt.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:256
 * @route "http://localhost/goods-receipts/{goodsReceipt}/cancel"
 */
cancel.patch = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: cancel.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:256
 * @route "http://localhost/goods-receipts/{goodsReceipt}/cancel"
 */
const cancelForm = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: cancel.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:256
 * @route "http://localhost/goods-receipts/{goodsReceipt}/cancel"
 */
cancelForm.patch = (
    args:
        | { goodsReceipt: number | { id: number } }
        | [goodsReceipt: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: cancel.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

cancel.form = cancelForm;
/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::approvedPurchaseOrders
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:171
 * @route "http://localhost/goods-receipts/approved-purchase-orders"
 */
export const approvedPurchaseOrders = (
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: approvedPurchaseOrders.url(options),
    method: 'get',
});

approvedPurchaseOrders.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/goods-receipts/approved-purchase-orders',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::approvedPurchaseOrders
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:171
 * @route "http://localhost/goods-receipts/approved-purchase-orders"
 */
approvedPurchaseOrders.url = (options?: RouteQueryOptions) => {
    return approvedPurchaseOrders.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::approvedPurchaseOrders
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:171
 * @route "http://localhost/goods-receipts/approved-purchase-orders"
 */
approvedPurchaseOrders.get = (
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: approvedPurchaseOrders.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::approvedPurchaseOrders
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:171
 * @route "http://localhost/goods-receipts/approved-purchase-orders"
 */
approvedPurchaseOrders.head = (
    options?: RouteQueryOptions,
): RouteDefinition<'head'> => ({
    url: approvedPurchaseOrders.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::approvedPurchaseOrders
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:171
 * @route "http://localhost/goods-receipts/approved-purchase-orders"
 */
const approvedPurchaseOrdersForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: approvedPurchaseOrders.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::approvedPurchaseOrders
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:171
 * @route "http://localhost/goods-receipts/approved-purchase-orders"
 */
approvedPurchaseOrdersForm.get = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: approvedPurchaseOrders.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\GoodsReceipt\GoodsReceiptController::approvedPurchaseOrders
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/GoodsReceipt/GoodsReceiptController.php:171
 * @route "http://localhost/goods-receipts/approved-purchase-orders"
 */
approvedPurchaseOrdersForm.head = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: approvedPurchaseOrders.url(formSafeOptions('head', options)),
    method: 'get',
});

approvedPurchaseOrders.form = approvedPurchaseOrdersForm;

const GoodsReceiptController = {
    index,
    create,
    store,
    approve,
    reject,
    cancel,
    approvedPurchaseOrders,
};

export default GoodsReceiptController;
