// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import GoodsReceiptController from "./GoodsReceiptController";

export const GoodsReceipt = {
    GoodsReceiptController,
}

export default GoodsReceipt