// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import dataLoading from './data-loading';
import errors from './errors';
import events from './events';
import forms from './forms';
import http from './http';
import layouts from './layouts';
import navigation from './navigation';
import prefetching from './prefetching';
import state from './state';

export const features = {
    dataLoading,
    http,
    errors,
    state,
    prefetching,
    layouts,
    navigation,
    events,
    forms,
};

export default features;
