// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    applyUrlDefaults,
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../index';

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:59
 * @route "http://localhost/stock-movements/stock-settlements/approve"
 */
export const approve = (
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: approve.url(options),
    method: 'post',
});

approve.definition = {
    methods: ['post'],
    url: 'http://localhost/stock-movements/stock-settlements/approve',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:59
 * @route "http://localhost/stock-movements/stock-settlements/approve"
 */
approve.url = (options?: RouteQueryOptions) => {
    return approve.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:59
 * @route "http://localhost/stock-movements/stock-settlements/approve"
 */
approve.post = (options?: RouteQueryOptions): RouteDefinition<'post'> => ({
    url: approve.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:59
 * @route "http://localhost/stock-movements/stock-settlements/approve"
 */
const approveForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: approve.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:59
 * @route "http://localhost/stock-movements/stock-settlements/approve"
 */
approveForm.post = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: approve.url(options),
    method: 'post',
});

approve.form = approveForm;
/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:152
 * @route "http://localhost/stock-movements/stock-settlements/reject"
 */
export const reject = (
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: reject.url(options),
    method: 'post',
});

reject.definition = {
    methods: ['post'],
    url: 'http://localhost/stock-movements/stock-settlements/reject',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:152
 * @route "http://localhost/stock-movements/stock-settlements/reject"
 */
reject.url = (options?: RouteQueryOptions) => {
    return reject.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:152
 * @route "http://localhost/stock-movements/stock-settlements/reject"
 */
reject.post = (options?: RouteQueryOptions): RouteDefinition<'post'> => ({
    url: reject.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:152
 * @route "http://localhost/stock-movements/stock-settlements/reject"
 */
const rejectForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: reject.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:152
 * @route "http://localhost/stock-movements/stock-settlements/reject"
 */
rejectForm.post = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: reject.url(options),
    method: 'post',
});

reject.form = rejectForm;
/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:40
 * @route "http://localhost/stock-movements/stock-settlements/{invoice}"
 */
export const show = (
    args:
        | { invoice: number | { id: number } }
        | [invoice: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: show.url(args, options),
    method: 'get',
});

show.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/stock-movements/stock-settlements/{invoice}',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:40
 * @route "http://localhost/stock-movements/stock-settlements/{invoice}"
 */
show.url = (
    args:
        | { invoice: number | { id: number } }
        | [invoice: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { invoice: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { invoice: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            invoice: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        invoice:
            typeof args.invoice === 'object' ? args.invoice.id : args.invoice,
    };

    return (
        show.definition.url
            .replace('{invoice}', parsedArgs.invoice.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:40
 * @route "http://localhost/stock-movements/stock-settlements/{invoice}"
 */
show.get = (
    args:
        | { invoice: number | { id: number } }
        | [invoice: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: show.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:40
 * @route "http://localhost/stock-movements/stock-settlements/{invoice}"
 */
show.head = (
    args:
        | { invoice: number | { id: number } }
        | [invoice: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'head'> => ({
    url: show.url(args, options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:40
 * @route "http://localhost/stock-movements/stock-settlements/{invoice}"
 */
const showForm = (
    args:
        | { invoice: number | { id: number } }
        | [invoice: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: show.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:40
 * @route "http://localhost/stock-movements/stock-settlements/{invoice}"
 */
showForm.get = (
    args:
        | { invoice: number | { id: number } }
        | [invoice: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: show.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockSettlementController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockSettlementController.php:40
 * @route "http://localhost/stock-movements/stock-settlements/{invoice}"
 */
showForm.head = (
    args:
        | { invoice: number | { id: number } }
        | [invoice: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: show.url(args, formSafeOptions('head', options)),
    method: 'get',
});

show.form = showForm;

const stockSettlements = {
    approve,
    reject,
    show,
};

export default stockSettlements;
