// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import picture from "./picture";

export const profile = {
    picture,
}

export default profile