// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../index';

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::destroyLogs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:102
 * @route "http://localhost/access-control/printer-logs"
 */
export const destroy = (
    options?: RouteQueryOptions,
): RouteDefinition<'delete'> => ({
    url: destroy.url(options),
    method: 'delete',
});

destroy.definition = {
    methods: ['delete'],
    url: 'http://localhost/access-control/printer-logs',
} satisfies RouteDefinition<['delete']>;

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::destroyLogs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:102
 * @route "http://localhost/access-control/printer-logs"
 */
destroy.url = (options?: RouteQueryOptions) => {
    return destroy.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::destroyLogs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:102
 * @route "http://localhost/access-control/printer-logs"
 */
destroy.delete = (options?: RouteQueryOptions): RouteDefinition<'delete'> => ({
    url: destroy.url(options),
    method: 'delete',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::destroyLogs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:102
 * @route "http://localhost/access-control/printer-logs"
 */
const destroyForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: destroy.url(formSafeOptions('delete', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\AccessControl\PrinterController::destroyLogs
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/AccessControl/PrinterController.php:102
 * @route "http://localhost/access-control/printer-logs"
 */
destroyForm.delete = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: destroy.url(formSafeOptions('delete', options)),
    method: 'post',
});

destroy.form = destroyForm;

const printerLogs = {
    destroy,
};

export default printerLogs;
