// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    applyUrlDefaults,
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../index';

/**
 * @see \App\Http\Controllers\Users\UserController::updatePermissions
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Users/UserController.php:118
 * @route "http://localhost/users/{user}/permissions"
 */
export const update = (
    args:
        | { user: number | { id: number } }
        | [user: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: update.url(args, options),
    method: 'patch',
});

update.definition = {
    methods: ['patch'],
    url: 'http://localhost/users/{user}/permissions',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\Users\UserController::updatePermissions
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Users/UserController.php:118
 * @route "http://localhost/users/{user}/permissions"
 */
update.url = (
    args:
        | { user: number | { id: number } }
        | [user: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { user: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { user: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            user: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        user: typeof args.user === 'object' ? args.user.id : args.user,
    };

    return (
        update.definition.url
            .replace('{user}', parsedArgs.user.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\Users\UserController::updatePermissions
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Users/UserController.php:118
 * @route "http://localhost/users/{user}/permissions"
 */
update.patch = (
    args:
        | { user: number | { id: number } }
        | [user: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: update.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\Users\UserController::updatePermissions
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Users/UserController.php:118
 * @route "http://localhost/users/{user}/permissions"
 */
const updateForm = (
    args:
        | { user: number | { id: number } }
        | [user: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: update.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Users\UserController::updatePermissions
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Users/UserController.php:118
 * @route "http://localhost/users/{user}/permissions"
 */
updateForm.patch = (
    args:
        | { user: number | { id: number } }
        | [user: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: update.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

update.form = updateForm;

const permissions = {
    update,
};

export default permissions;
