// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../index";
import menuPriceListsAde053f from "./menu-price-lists";

/**
 * @see \App\Http\Controllers\MasterData\ProductController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\ProductController.php:21
 * @route "http://localhost:8000/master-data/products"
 */
export const products = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: products.url(options),
    method: "get",
})

products.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/master-data/products",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\MasterData\ProductController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\ProductController.php:21
 * @route "http://localhost:8000/master-data/products"
 */
products.url = (options?: RouteQueryOptions) => {
    return products.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\ProductController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\ProductController.php:21
 * @route "http://localhost:8000/master-data/products"
 */
products.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: products.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\ProductController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\ProductController.php:21
 * @route "http://localhost:8000/master-data/products"
 */
products.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: products.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\MasterData\ProductController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\ProductController.php:21
 * @route "http://localhost:8000/master-data/products"
 */
const productsForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: products.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\ProductController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\ProductController.php:21
 * @route "http://localhost:8000/master-data/products"
 */
productsForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: products.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\ProductController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\ProductController.php:21
 * @route "http://localhost:8000/master-data/products"
 */
productsForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: products.url(formSafeOptions("head", options)),
    method: "get",
})



products.form = productsForm
/**
 * @see \App\Http\Controllers\MasterData\CompanyBranchController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CompanyBranchController.php:15
 * @route "http://localhost:8000/master-data/company-branches"
 */
export const companyBranches = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: companyBranches.url(options),
    method: "get",
})

companyBranches.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/master-data/company-branches",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\MasterData\CompanyBranchController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CompanyBranchController.php:15
 * @route "http://localhost:8000/master-data/company-branches"
 */
companyBranches.url = (options?: RouteQueryOptions) => {
    return companyBranches.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\CompanyBranchController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CompanyBranchController.php:15
 * @route "http://localhost:8000/master-data/company-branches"
 */
companyBranches.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: companyBranches.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\CompanyBranchController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CompanyBranchController.php:15
 * @route "http://localhost:8000/master-data/company-branches"
 */
companyBranches.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: companyBranches.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\MasterData\CompanyBranchController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CompanyBranchController.php:15
 * @route "http://localhost:8000/master-data/company-branches"
 */
const companyBranchesForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: companyBranches.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\CompanyBranchController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CompanyBranchController.php:15
 * @route "http://localhost:8000/master-data/company-branches"
 */
companyBranchesForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: companyBranches.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\CompanyBranchController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CompanyBranchController.php:15
 * @route "http://localhost:8000/master-data/company-branches"
 */
companyBranchesForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: companyBranches.url(formSafeOptions("head", options)),
    method: "get",
})



companyBranches.form = companyBranchesForm
/**
 * @see \App\Http\Controllers\MasterData\CustomerController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:13
 * @route "http://localhost:8000/master-data/customers"
 */
export const customers = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: customers.url(options),
    method: "get",
})

customers.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/master-data/customers",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:13
 * @route "http://localhost:8000/master-data/customers"
 */
customers.url = (options?: RouteQueryOptions) => {
    return customers.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:13
 * @route "http://localhost:8000/master-data/customers"
 */
customers.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: customers.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:13
 * @route "http://localhost:8000/master-data/customers"
 */
customers.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: customers.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\MasterData\CustomerController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:13
 * @route "http://localhost:8000/master-data/customers"
 */
const customersForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: customers.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:13
 * @route "http://localhost:8000/master-data/customers"
 */
customersForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: customers.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\CustomerController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\CustomerController.php:13
 * @route "http://localhost:8000/master-data/customers"
 */
customersForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: customers.url(formSafeOptions("head", options)),
    method: "get",
})



customers.form = customersForm
/**
 * @see \App\Http\Controllers\MasterData\ExchangeRateController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\ExchangeRateController.php:12
 * @route "http://localhost:8000/master-data/exchange-rates"
 */
export const exchangeRates = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: exchangeRates.url(options),
    method: "get",
})

exchangeRates.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/master-data/exchange-rates",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\MasterData\ExchangeRateController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\ExchangeRateController.php:12
 * @route "http://localhost:8000/master-data/exchange-rates"
 */
exchangeRates.url = (options?: RouteQueryOptions) => {
    return exchangeRates.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\ExchangeRateController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\ExchangeRateController.php:12
 * @route "http://localhost:8000/master-data/exchange-rates"
 */
exchangeRates.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: exchangeRates.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\ExchangeRateController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\ExchangeRateController.php:12
 * @route "http://localhost:8000/master-data/exchange-rates"
 */
exchangeRates.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: exchangeRates.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\MasterData\ExchangeRateController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\ExchangeRateController.php:12
 * @route "http://localhost:8000/master-data/exchange-rates"
 */
const exchangeRatesForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: exchangeRates.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\ExchangeRateController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\ExchangeRateController.php:12
 * @route "http://localhost:8000/master-data/exchange-rates"
 */
exchangeRatesForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: exchangeRates.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\ExchangeRateController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\ExchangeRateController.php:12
 * @route "http://localhost:8000/master-data/exchange-rates"
 */
exchangeRatesForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: exchangeRates.url(formSafeOptions("head", options)),
    method: "get",
})



exchangeRates.form = exchangeRatesForm
/**
 * @see \App\Http\Controllers\MasterData\MenuController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuController.php:21
 * @route "http://localhost:8000/master-data/menu"
 */
export const menu = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: menu.url(options),
    method: "get",
})

menu.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/master-data/menu",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\MasterData\MenuController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuController.php:21
 * @route "http://localhost:8000/master-data/menu"
 */
menu.url = (options?: RouteQueryOptions) => {
    return menu.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\MenuController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuController.php:21
 * @route "http://localhost:8000/master-data/menu"
 */
menu.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: menu.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\MenuController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuController.php:21
 * @route "http://localhost:8000/master-data/menu"
 */
menu.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: menu.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\MasterData\MenuController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuController.php:21
 * @route "http://localhost:8000/master-data/menu"
 */
const menuForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: menu.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\MenuController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuController.php:21
 * @route "http://localhost:8000/master-data/menu"
 */
menuForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: menu.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\MenuController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuController.php:21
 * @route "http://localhost:8000/master-data/menu"
 */
menuForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: menu.url(formSafeOptions("head", options)),
    method: "get",
})



menu.form = menuForm
/**
 * @see \App\Http\Controllers\MasterData\MenuPriceListController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuPriceListController.php:18
 * @route "http://localhost:8000/master-data/menu-price-lists"
 */
export const menuPriceLists = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: menuPriceLists.url(options),
    method: "get",
})

menuPriceLists.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/master-data/menu-price-lists",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\MasterData\MenuPriceListController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuPriceListController.php:18
 * @route "http://localhost:8000/master-data/menu-price-lists"
 */
menuPriceLists.url = (options?: RouteQueryOptions) => {
    return menuPriceLists.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\MenuPriceListController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuPriceListController.php:18
 * @route "http://localhost:8000/master-data/menu-price-lists"
 */
menuPriceLists.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: menuPriceLists.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\MenuPriceListController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuPriceListController.php:18
 * @route "http://localhost:8000/master-data/menu-price-lists"
 */
menuPriceLists.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: menuPriceLists.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\MasterData\MenuPriceListController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuPriceListController.php:18
 * @route "http://localhost:8000/master-data/menu-price-lists"
 */
const menuPriceListsForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: menuPriceLists.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\MenuPriceListController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuPriceListController.php:18
 * @route "http://localhost:8000/master-data/menu-price-lists"
 */
menuPriceListsForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: menuPriceLists.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\MenuPriceListController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\MenuPriceListController.php:18
 * @route "http://localhost:8000/master-data/menu-price-lists"
 */
menuPriceListsForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: menuPriceLists.url(formSafeOptions("head", options)),
    method: "get",
})



menuPriceLists.form = menuPriceListsForm
/**
 * @see \App\Http\Controllers\MasterData\PosTerminalController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\PosTerminalController.php:13
 * @route "http://localhost:8000/master-data/pos-terminals"
 */
export const posTerminals = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: posTerminals.url(options),
    method: "get",
})

posTerminals.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/master-data/pos-terminals",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\MasterData\PosTerminalController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\PosTerminalController.php:13
 * @route "http://localhost:8000/master-data/pos-terminals"
 */
posTerminals.url = (options?: RouteQueryOptions) => {
    return posTerminals.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\PosTerminalController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\PosTerminalController.php:13
 * @route "http://localhost:8000/master-data/pos-terminals"
 */
posTerminals.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: posTerminals.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\PosTerminalController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\PosTerminalController.php:13
 * @route "http://localhost:8000/master-data/pos-terminals"
 */
posTerminals.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: posTerminals.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\MasterData\PosTerminalController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\PosTerminalController.php:13
 * @route "http://localhost:8000/master-data/pos-terminals"
 */
const posTerminalsForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: posTerminals.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\PosTerminalController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\PosTerminalController.php:13
 * @route "http://localhost:8000/master-data/pos-terminals"
 */
posTerminalsForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: posTerminals.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\PosTerminalController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\PosTerminalController.php:13
 * @route "http://localhost:8000/master-data/pos-terminals"
 */
posTerminalsForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: posTerminals.url(formSafeOptions("head", options)),
    method: "get",
})



posTerminals.form = posTerminalsForm
/**
 * @see \App\Http\Controllers\MasterData\DiningResourceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\DiningResourceController.php:13
 * @route "http://localhost:8000/master-data/seats"
 */
export const seats = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: seats.url(options),
    method: "get",
})

seats.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/master-data/seats",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\MasterData\DiningResourceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\DiningResourceController.php:13
 * @route "http://localhost:8000/master-data/seats"
 */
seats.url = (options?: RouteQueryOptions) => {
    return seats.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\DiningResourceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\DiningResourceController.php:13
 * @route "http://localhost:8000/master-data/seats"
 */
seats.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: seats.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\DiningResourceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\DiningResourceController.php:13
 * @route "http://localhost:8000/master-data/seats"
 */
seats.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: seats.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\MasterData\DiningResourceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\DiningResourceController.php:13
 * @route "http://localhost:8000/master-data/seats"
 */
const seatsForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: seats.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\DiningResourceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\DiningResourceController.php:13
 * @route "http://localhost:8000/master-data/seats"
 */
seatsForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: seats.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\DiningResourceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\DiningResourceController.php:13
 * @route "http://localhost:8000/master-data/seats"
 */
seatsForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: seats.url(formSafeOptions("head", options)),
    method: "get",
})



seats.form = seatsForm
/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\SupplierController.php:12
 * @route "http://localhost:8000/master-data/suppliers"
 */
export const suppliers = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: suppliers.url(options),
    method: "get",
})

suppliers.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/master-data/suppliers",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\SupplierController.php:12
 * @route "http://localhost:8000/master-data/suppliers"
 */
suppliers.url = (options?: RouteQueryOptions) => {
    return suppliers.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\SupplierController.php:12
 * @route "http://localhost:8000/master-data/suppliers"
 */
suppliers.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: suppliers.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\SupplierController.php:12
 * @route "http://localhost:8000/master-data/suppliers"
 */
suppliers.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: suppliers.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\SupplierController.php:12
 * @route "http://localhost:8000/master-data/suppliers"
 */
const suppliersForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: suppliers.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\SupplierController.php:12
 * @route "http://localhost:8000/master-data/suppliers"
 */
suppliersForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: suppliers.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\SupplierController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\SupplierController.php:12
 * @route "http://localhost:8000/master-data/suppliers"
 */
suppliersForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: suppliers.url(formSafeOptions("head", options)),
    method: "get",
})



suppliers.form = suppliersForm
/**
 * @see \App\Http\Controllers\MasterData\TaxController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\TaxController.php:12
 * @route "http://localhost:8000/master-data/taxes"
 */
export const taxes = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: taxes.url(options),
    method: "get",
})

taxes.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/master-data/taxes",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\MasterData\TaxController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\TaxController.php:12
 * @route "http://localhost:8000/master-data/taxes"
 */
taxes.url = (options?: RouteQueryOptions) => {
    return taxes.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\TaxController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\TaxController.php:12
 * @route "http://localhost:8000/master-data/taxes"
 */
taxes.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: taxes.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\TaxController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\TaxController.php:12
 * @route "http://localhost:8000/master-data/taxes"
 */
taxes.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: taxes.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\MasterData\TaxController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\TaxController.php:12
 * @route "http://localhost:8000/master-data/taxes"
 */
const taxesForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: taxes.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\TaxController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\TaxController.php:12
 * @route "http://localhost:8000/master-data/taxes"
 */
taxesForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: taxes.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\TaxController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\TaxController.php:12
 * @route "http://localhost:8000/master-data/taxes"
 */
taxesForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: taxes.url(formSafeOptions("head", options)),
    method: "get",
})



taxes.form = taxesForm
/**
 * @see \App\Http\Controllers\MasterData\WarehouseLocationController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\WarehouseLocationController.php:13
 * @route "http://localhost:8000/master-data/warehouse-locations"
 */
export const warehouseLocations = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: warehouseLocations.url(options),
    method: "get",
})

warehouseLocations.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/master-data/warehouse-locations",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\MasterData\WarehouseLocationController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\WarehouseLocationController.php:13
 * @route "http://localhost:8000/master-data/warehouse-locations"
 */
warehouseLocations.url = (options?: RouteQueryOptions) => {
    return warehouseLocations.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\MasterData\WarehouseLocationController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\WarehouseLocationController.php:13
 * @route "http://localhost:8000/master-data/warehouse-locations"
 */
warehouseLocations.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: warehouseLocations.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\WarehouseLocationController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\WarehouseLocationController.php:13
 * @route "http://localhost:8000/master-data/warehouse-locations"
 */
warehouseLocations.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: warehouseLocations.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\MasterData\WarehouseLocationController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\WarehouseLocationController.php:13
 * @route "http://localhost:8000/master-data/warehouse-locations"
 */
const warehouseLocationsForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: warehouseLocations.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\WarehouseLocationController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\WarehouseLocationController.php:13
 * @route "http://localhost:8000/master-data/warehouse-locations"
 */
warehouseLocationsForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: warehouseLocations.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\MasterData\WarehouseLocationController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\MasterData\WarehouseLocationController.php:13
 * @route "http://localhost:8000/master-data/warehouse-locations"
 */
warehouseLocationsForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: warehouseLocations.url(formSafeOptions("head", options)),
    method: "get",
})



warehouseLocations.form = warehouseLocationsForm

const masterData = {
    products,
    "company-branches": companyBranches,
    customers,
    "exchange-rates": exchangeRates,
    menu,
    "menu-price-lists": menuPriceLists,
    "pos-terminals": posTerminals,
    seats,
    suppliers,
    taxes,
    "warehouse-locations": warehouseLocations,
    menuPriceLists: Object.assign(menuPriceLists, menuPriceListsAde053f),
}

export default masterData