// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::addItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:167
 * @route "http://localhost:8000/orders/{diningSession}/items"
 */
export const add = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: add.url(args, options),
    method: "post",
})

add.definition = {
    methods: ["post"],
    url: "http://localhost:8000/orders/{diningSession}/items",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::addItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:167
 * @route "http://localhost:8000/orders/{diningSession}/items"
 */
add.url = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { diningSession: args }
}
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
    args = { diningSession: args.id }
}
    
    if (Array.isArray(args)) {
    args = {
        diningSession: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        diningSession: typeof args.diningSession === "object" ? args.diningSession.id : args.diningSession,
    }
    
    return add.definition.url
        .replace("{diningSession}", parsedArgs.diningSession.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::addItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:167
 * @route "http://localhost:8000/orders/{diningSession}/items"
 */
add.post = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: add.url(args, options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::addItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:167
 * @route "http://localhost:8000/orders/{diningSession}/items"
 */
const addForm = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: add.url(args, options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::addItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:167
 * @route "http://localhost:8000/orders/{diningSession}/items"
 */
addForm.post = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: add.url(args, options),
    method: "post",
})



add.form = addForm
/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::updateItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:347
 * @route "http://localhost:8000/orders/{diningSession}/items/{orderLine}"
 */
export const update = (args: { diningSession: number | { id: number }, orderLine: number | { id: number } } | [ diningSession: number | { id: number }, orderLine: number | { id: number } ], options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: update.url(args, options),
    method: "patch",
})

update.definition = {
    methods: ["patch"],
    url: "http://localhost:8000/orders/{diningSession}/items/{orderLine}",
} satisfies RouteDefinition<["patch"]>

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::updateItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:347
 * @route "http://localhost:8000/orders/{diningSession}/items/{orderLine}"
 */
update.url = (args: { diningSession: number | { id: number }, orderLine: number | { id: number } } | [ diningSession: number | { id: number }, orderLine: number | { id: number } ], options?: RouteQueryOptions) => {
    if (Array.isArray(args)) {
    args = {
        diningSession: args[0],
        orderLine: args[1],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        diningSession: typeof args.diningSession === "object" ? args.diningSession.id : args.diningSession,
        orderLine: typeof args.orderLine === "object" ? args.orderLine.id : args.orderLine,
    }
    
    return update.definition.url
        .replace("{diningSession}", parsedArgs.diningSession.toString())
        .replace("{orderLine}", parsedArgs.orderLine.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::updateItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:347
 * @route "http://localhost:8000/orders/{diningSession}/items/{orderLine}"
 */
update.patch = (args: { diningSession: number | { id: number }, orderLine: number | { id: number } } | [ diningSession: number | { id: number }, orderLine: number | { id: number } ], options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: update.url(args, options),
    method: "patch",
})



/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::updateItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:347
 * @route "http://localhost:8000/orders/{diningSession}/items/{orderLine}"
 */
const updateForm = (args: { diningSession: number | { id: number }, orderLine: number | { id: number } } | [ diningSession: number | { id: number }, orderLine: number | { id: number } ], options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: update.url(args, formSafeOptions("patch", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::updateItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:347
 * @route "http://localhost:8000/orders/{diningSession}/items/{orderLine}"
 */
updateForm.patch = (args: { diningSession: number | { id: number }, orderLine: number | { id: number } } | [ diningSession: number | { id: number }, orderLine: number | { id: number } ], options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: update.url(args, formSafeOptions("patch", options)),
    method: "post",
})



update.form = updateForm
/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::clearItems
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:377
 * @route "http://localhost:8000/orders/{diningSession}/items"
 */
export const clear = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: clear.url(args, options),
    method: "delete",
})

clear.definition = {
    methods: ["delete"],
    url: "http://localhost:8000/orders/{diningSession}/items",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::clearItems
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:377
 * @route "http://localhost:8000/orders/{diningSession}/items"
 */
clear.url = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { diningSession: args }
}
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
    args = { diningSession: args.id }
}
    
    if (Array.isArray(args)) {
    args = {
        diningSession: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        diningSession: typeof args.diningSession === "object" ? args.diningSession.id : args.diningSession,
    }
    
    return clear.definition.url
        .replace("{diningSession}", parsedArgs.diningSession.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::clearItems
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:377
 * @route "http://localhost:8000/orders/{diningSession}/items"
 */
clear.delete = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: clear.url(args, options),
    method: "delete",
})



/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::clearItems
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:377
 * @route "http://localhost:8000/orders/{diningSession}/items"
 */
const clearForm = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: clear.url(args, formSafeOptions("delete", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::clearItems
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:377
 * @route "http://localhost:8000/orders/{diningSession}/items"
 */
clearForm.delete = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: clear.url(args, formSafeOptions("delete", options)),
    method: "post",
})



clear.form = clearForm
/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::removeItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:368
 * @route "http://localhost:8000/orders/{diningSession}/items/{orderLine}"
 */
export const remove = (args: { diningSession: number | { id: number }, orderLine: number | { id: number } } | [ diningSession: number | { id: number }, orderLine: number | { id: number } ], options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: remove.url(args, options),
    method: "delete",
})

remove.definition = {
    methods: ["delete"],
    url: "http://localhost:8000/orders/{diningSession}/items/{orderLine}",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::removeItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:368
 * @route "http://localhost:8000/orders/{diningSession}/items/{orderLine}"
 */
remove.url = (args: { diningSession: number | { id: number }, orderLine: number | { id: number } } | [ diningSession: number | { id: number }, orderLine: number | { id: number } ], options?: RouteQueryOptions) => {
    if (Array.isArray(args)) {
    args = {
        diningSession: args[0],
        orderLine: args[1],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        diningSession: typeof args.diningSession === "object" ? args.diningSession.id : args.diningSession,
        orderLine: typeof args.orderLine === "object" ? args.orderLine.id : args.orderLine,
    }
    
    return remove.definition.url
        .replace("{diningSession}", parsedArgs.diningSession.toString())
        .replace("{orderLine}", parsedArgs.orderLine.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::removeItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:368
 * @route "http://localhost:8000/orders/{diningSession}/items/{orderLine}"
 */
remove.delete = (args: { diningSession: number | { id: number }, orderLine: number | { id: number } } | [ diningSession: number | { id: number }, orderLine: number | { id: number } ], options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: remove.url(args, options),
    method: "delete",
})



/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::removeItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:368
 * @route "http://localhost:8000/orders/{diningSession}/items/{orderLine}"
 */
const removeForm = (args: { diningSession: number | { id: number }, orderLine: number | { id: number } } | [ diningSession: number | { id: number }, orderLine: number | { id: number } ], options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: remove.url(args, formSafeOptions("delete", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::removeItem
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:368
 * @route "http://localhost:8000/orders/{diningSession}/items/{orderLine}"
 */
removeForm.delete = (args: { diningSession: number | { id: number }, orderLine: number | { id: number } } | [ diningSession: number | { id: number }, orderLine: number | { id: number } ], options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: remove.url(args, formSafeOptions("delete", options)),
    method: "post",
})



remove.form = removeForm

const items = {
    add,
    update,
    clear,
    remove,
}

export default items