// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../index';

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:47
 * @route "http://localhost/login"
 */
export const login = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: login.url(options),
    method: 'get',
});

login.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/login',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:47
 * @route "http://localhost/login"
 */
login.url = (options?: RouteQueryOptions) => {
    return login.definition.url + queryParams(options);
};

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:47
 * @route "http://localhost/login"
 */
login.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: login.url(options),
    method: 'get',
});

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:47
 * @route "http://localhost/login"
 */
login.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: login.url(options),
    method: 'head',
});

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:47
 * @route "http://localhost/login"
 */
const loginForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: login.url(options),
    method: 'get',
});

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:47
 * @route "http://localhost/login"
 */
loginForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: login.url(options),
    method: 'get',
});

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::create
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:47
 * @route "http://localhost/login"
 */
loginForm.head = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: login.url(formSafeOptions('head', options)),
    method: 'get',
});

login.form = loginForm;
/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::destroy
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:100
 * @route "http://localhost/logout"
 */
export const logout = (
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: logout.url(options),
    method: 'post',
});

logout.definition = {
    methods: ['post'],
    url: 'http://localhost/logout',
} satisfies RouteDefinition<['post']>;

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::destroy
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:100
 * @route "http://localhost/logout"
 */
logout.url = (options?: RouteQueryOptions) => {
    return logout.definition.url + queryParams(options);
};

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::destroy
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:100
 * @route "http://localhost/logout"
 */
logout.post = (options?: RouteQueryOptions): RouteDefinition<'post'> => ({
    url: logout.url(options),
    method: 'post',
});

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::destroy
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:100
 * @route "http://localhost/logout"
 */
const logoutForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: logout.url(options),
    method: 'post',
});

/**
 * @see \Laravel\Fortify\Http\Controllers\AuthenticatedSessionController::destroy
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/fortify/src/Http/Controllers/AuthenticatedSessionController.php:100
 * @route "http://localhost/logout"
 */
logoutForm.post = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: logout.url(options),
    method: 'post',
});

logout.form = logoutForm;
/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
export const home = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: home.url(options),
    method: 'get',
});

home.definition = {
    methods: ['get', 'head', 'post', 'put', 'patch', 'delete', 'options'],
    url: 'http://localhost',
} satisfies RouteDefinition<
    ['get', 'head', 'post', 'put', 'patch', 'delete', 'options']
>;

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
home.url = (options?: RouteQueryOptions) => {
    return home.definition.url + queryParams(options);
};

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
home.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: home.url(options),
    method: 'get',
});

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
home.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: home.url(options),
    method: 'head',
});

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
home.post = (options?: RouteQueryOptions): RouteDefinition<'post'> => ({
    url: home.url(options),
    method: 'post',
});

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
home.put = (options?: RouteQueryOptions): RouteDefinition<'put'> => ({
    url: home.url(options),
    method: 'put',
});

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
home.patch = (options?: RouteQueryOptions): RouteDefinition<'patch'> => ({
    url: home.url(options),
    method: 'patch',
});

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
home.delete = (options?: RouteQueryOptions): RouteDefinition<'delete'> => ({
    url: home.url(options),
    method: 'delete',
});

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
home.options = (options?: RouteQueryOptions): RouteDefinition<'options'> => ({
    url: home.url(options),
    method: 'options',
});

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
const homeForm = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: home.url(options),
    method: 'get',
});

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
homeForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: home.url(options),
    method: 'get',
});

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
homeForm.head = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: home.url(formSafeOptions('head', options)),
    method: 'get',
});

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
homeForm.post = (options?: RouteQueryOptions): RouteFormDefinition<'post'> => ({
    action: home.url(options),
    method: 'post',
});

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
homeForm.put = (options?: RouteQueryOptions): RouteFormDefinition<'post'> => ({
    action: home.url(formSafeOptions('put', options)),
    method: 'post',
});

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
homeForm.patch = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: home.url(formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
homeForm.delete = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: home.url(formSafeOptions('delete', options)),
    method: 'post',
});

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see /home/runner/work/dmpos/dmpos/vendor/laravel/framework/src/Illuminate/Routing/RedirectController.php:19
 * @route "http://localhost"
 */
homeForm.options = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: home.url(formSafeOptions('options', options)),
    method: 'get',
});

home.form = homeForm;
/**
 * @see \App\Http\Controllers\Crm\DashboardController::__invoke
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Crm/DashboardController.php:14
 * @route "http://localhost/dashboard"
 */
export const dashboard = (
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: dashboard.url(options),
    method: 'get',
});

dashboard.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/dashboard',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\Crm\DashboardController::__invoke
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Crm/DashboardController.php:14
 * @route "http://localhost/dashboard"
 */
dashboard.url = (options?: RouteQueryOptions) => {
    return dashboard.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\Crm\DashboardController::__invoke
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Crm/DashboardController.php:14
 * @route "http://localhost/dashboard"
 */
dashboard.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: dashboard.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Crm\DashboardController::__invoke
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Crm/DashboardController.php:14
 * @route "http://localhost/dashboard"
 */
dashboard.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: dashboard.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\Crm\DashboardController::__invoke
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Crm/DashboardController.php:14
 * @route "http://localhost/dashboard"
 */
const dashboardForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: dashboard.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Crm\DashboardController::__invoke
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Crm/DashboardController.php:14
 * @route "http://localhost/dashboard"
 */
dashboardForm.get = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: dashboard.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Crm\DashboardController::__invoke
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Crm/DashboardController.php:14
 * @route "http://localhost/dashboard"
 */
dashboardForm.head = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: dashboard.url(formSafeOptions('head', options)),
    method: 'get',
});

dashboard.form = dashboardForm;

const routes = {
    login,
    logout,
    home,
    dashboard,
};

export default routes;
