// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \App\Http\Controllers\POS\PosSessionController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:17
 * @route "http://127.0.0.1:8000/pos-sessions"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "http://127.0.0.1:8000/pos-sessions",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\POS\PosSessionController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:17
 * @route "http://127.0.0.1:8000/pos-sessions"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\POS\PosSessionController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:17
 * @route "http://127.0.0.1:8000/pos-sessions"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\POS\PosSessionController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:17
 * @route "http://127.0.0.1:8000/pos-sessions"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\POS\PosSessionController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:17
 * @route "http://127.0.0.1:8000/pos-sessions"
 */
const indexForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\POS\PosSessionController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:17
 * @route "http://127.0.0.1:8000/pos-sessions"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\POS\PosSessionController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:17
 * @route "http://127.0.0.1:8000/pos-sessions"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(formSafeOptions("head", options)),
    method: "get",
})



index.form = indexForm
/**
 * @see \App\Http\Controllers\POS\PosSessionController::open
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:46
 * @route "http://127.0.0.1:8000/pos-sessions/open"
 */
export const open = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: open.url(options),
    method: "post",
})

open.definition = {
    methods: ["post"],
    url: "http://127.0.0.1:8000/pos-sessions/open",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\POS\PosSessionController::open
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:46
 * @route "http://127.0.0.1:8000/pos-sessions/open"
 */
open.url = (options?: RouteQueryOptions) => {
    return open.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\POS\PosSessionController::open
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:46
 * @route "http://127.0.0.1:8000/pos-sessions/open"
 */
open.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: open.url(options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\POS\PosSessionController::open
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:46
 * @route "http://127.0.0.1:8000/pos-sessions/open"
 */
const openForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: open.url(options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\POS\PosSessionController::open
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:46
 * @route "http://127.0.0.1:8000/pos-sessions/open"
 */
openForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: open.url(options),
    method: "post",
})



open.form = openForm
/**
 * @see \App\Http\Controllers\POS\PosSessionController::close
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:119
 * @route "http://127.0.0.1:8000/pos-sessions/{posSession}/close"
 */
export const close = (args: { posSession: number | { id: number } } | [ posSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: close.url(args, options),
    method: "post",
})

close.definition = {
    methods: ["post"],
    url: "http://127.0.0.1:8000/pos-sessions/{posSession}/close",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\POS\PosSessionController::close
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:119
 * @route "http://127.0.0.1:8000/pos-sessions/{posSession}/close"
 */
close.url = (args: { posSession: number | { id: number } } | [ posSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { posSession: args }
}
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
    args = { posSession: args.id }
}
    
    if (Array.isArray(args)) {
    args = {
        posSession: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        posSession: typeof args.posSession === "object" ? args.posSession.id : args.posSession,
    }
    
    return close.definition.url
        .replace("{posSession}", parsedArgs.posSession.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\POS\PosSessionController::close
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:119
 * @route "http://127.0.0.1:8000/pos-sessions/{posSession}/close"
 */
close.post = (args: { posSession: number | { id: number } } | [ posSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: close.url(args, options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\POS\PosSessionController::close
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:119
 * @route "http://127.0.0.1:8000/pos-sessions/{posSession}/close"
 */
const closeForm = (args: { posSession: number | { id: number } } | [ posSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: close.url(args, options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\POS\PosSessionController::close
 * @see \D:\Lar\dmpos\app\Http\Controllers\POS\PosSessionController.php:119
 * @route "http://127.0.0.1:8000/pos-sessions/{posSession}/close"
 */
closeForm.post = (args: { posSession: number | { id: number } } | [ posSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: close.url(args, options),
    method: "post",
})



close.form = closeForm

const PosSessionController = {
    index,
    open,
    close,
}

export default PosSessionController