// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../index";
import invoices from "./invoices";

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:19
 * @route "http://localhost:8000/sales"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/sales",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:19
 * @route "http://localhost:8000/sales"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:19
 * @route "http://localhost:8000/sales"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:19
 * @route "http://localhost:8000/sales"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:19
 * @route "http://localhost:8000/sales"
 */
const indexForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:19
 * @route "http://localhost:8000/sales"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:19
 * @route "http://localhost:8000/sales"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(formSafeOptions("head", options)),
    method: "get",
})



index.form = indexForm

const sales = {
    index,
    invoices,
}

export default sales