// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::cancelPayment
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:291
 * @route "http://127.0.0.1:8000/sales/payments/{payment}/cancel"
 */
export const cancel = (args: { payment: number | { id: number } } | [ payment: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: cancel.url(args, options),
    method: "patch",
})

cancel.definition = {
    methods: ["patch"],
    url: "http://127.0.0.1:8000/sales/payments/{payment}/cancel",
} satisfies RouteDefinition<["patch"]>

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::cancelPayment
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:291
 * @route "http://127.0.0.1:8000/sales/payments/{payment}/cancel"
 */
cancel.url = (args: { payment: number | { id: number } } | [ payment: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { payment: args }
}
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
    args = { payment: args.id }
}
    
    if (Array.isArray(args)) {
    args = {
        payment: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        payment: typeof args.payment === "object" ? args.payment.id : args.payment,
    }
    
    return cancel.definition.url
        .replace("{payment}", parsedArgs.payment.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::cancelPayment
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:291
 * @route "http://127.0.0.1:8000/sales/payments/{payment}/cancel"
 */
cancel.patch = (args: { payment: number | { id: number } } | [ payment: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: cancel.url(args, options),
    method: "patch",
})



/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::cancelPayment
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:291
 * @route "http://127.0.0.1:8000/sales/payments/{payment}/cancel"
 */
const cancelForm = (args: { payment: number | { id: number } } | [ payment: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: cancel.url(args, formSafeOptions("patch", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::cancelPayment
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:291
 * @route "http://127.0.0.1:8000/sales/payments/{payment}/cancel"
 */
cancelForm.patch = (args: { payment: number | { id: number } } | [ payment: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: cancel.url(args, formSafeOptions("patch", options)),
    method: "post",
})



cancel.form = cancelForm

const payments = {
    cancel,
}

export default payments