// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::saveManage
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:287
 * @route "http://127.0.0.1:8000/orders/{diningSession}/manage"
 */
export const save = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: save.url(args, options),
    method: "post",
})

save.definition = {
    methods: ["post"],
    url: "http://127.0.0.1:8000/orders/{diningSession}/manage",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::saveManage
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:287
 * @route "http://127.0.0.1:8000/orders/{diningSession}/manage"
 */
save.url = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { diningSession: args }
}
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
    args = { diningSession: args.id }
}
    
    if (Array.isArray(args)) {
    args = {
        diningSession: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        diningSession: typeof args.diningSession === "object" ? args.diningSession.id : args.diningSession,
    }
    
    return save.definition.url
        .replace("{diningSession}", parsedArgs.diningSession.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::saveManage
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:287
 * @route "http://127.0.0.1:8000/orders/{diningSession}/manage"
 */
save.post = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: save.url(args, options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::saveManage
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:287
 * @route "http://127.0.0.1:8000/orders/{diningSession}/manage"
 */
const saveForm = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: save.url(args, options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::saveManage
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:287
 * @route "http://127.0.0.1:8000/orders/{diningSession}/manage"
 */
saveForm.post = (args: { diningSession: number | { id: number } } | [ diningSession: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: save.url(args, options),
    method: "post",
})



save.form = saveForm

const manage = {
    save,
}

export default manage