// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    applyUrlDefaults,
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../index';
import currentInvoice from './current-invoice';
import customer from './customer';
import invoices from './invoices';
import items from './items';
import manageF1b31d3 from './manage';
import printJobs from './print-jobs';
import printLines from './print-lines';

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:38
 * @route "http://localhost/orders/{diningSession}/menu"
 */
export const show = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: show.url(args, options),
    method: 'get',
});

show.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/orders/{diningSession}/menu',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:38
 * @route "http://localhost/orders/{diningSession}/menu"
 */
show.url = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { diningSession: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { diningSession: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            diningSession: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        diningSession:
            typeof args.diningSession === 'object'
                ? args.diningSession.id
                : args.diningSession,
    };

    return (
        show.definition.url
            .replace('{diningSession}', parsedArgs.diningSession.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:38
 * @route "http://localhost/orders/{diningSession}/menu"
 */
show.get = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: show.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:38
 * @route "http://localhost/orders/{diningSession}/menu"
 */
show.head = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'head'> => ({
    url: show.url(args, options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:38
 * @route "http://localhost/orders/{diningSession}/menu"
 */
const showForm = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: show.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:38
 * @route "http://localhost/orders/{diningSession}/menu"
 */
showForm.get = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: show.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:38
 * @route "http://localhost/orders/{diningSession}/menu"
 */
showForm.head = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: show.url(args, formSafeOptions('head', options)),
    method: 'get',
});

show.form = showForm;
/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::manage
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:230
 * @route "http://localhost/orders/{diningSession}/manage"
 */
export const manage = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: manage.url(args, options),
    method: 'get',
});

manage.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/orders/{diningSession}/manage',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::manage
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:230
 * @route "http://localhost/orders/{diningSession}/manage"
 */
manage.url = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { diningSession: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { diningSession: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            diningSession: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        diningSession:
            typeof args.diningSession === 'object'
                ? args.diningSession.id
                : args.diningSession,
    };

    return (
        manage.definition.url
            .replace('{diningSession}', parsedArgs.diningSession.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::manage
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:230
 * @route "http://localhost/orders/{diningSession}/manage"
 */
manage.get = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: manage.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::manage
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:230
 * @route "http://localhost/orders/{diningSession}/manage"
 */
manage.head = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'head'> => ({
    url: manage.url(args, options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::manage
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:230
 * @route "http://localhost/orders/{diningSession}/manage"
 */
const manageForm = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: manage.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::manage
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:230
 * @route "http://localhost/orders/{diningSession}/manage"
 */
manageForm.get = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: manage.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::manage
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:230
 * @route "http://localhost/orders/{diningSession}/manage"
 */
manageForm.head = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: manage.url(args, formSafeOptions('head', options)),
    method: 'get',
});

manage.form = manageForm;
/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::sendToKitchen
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:394
 * @route "http://localhost/orders/{diningSession}/send-kitchen"
 */
export const sendKitchen = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: sendKitchen.url(args, options),
    method: 'post',
});

sendKitchen.definition = {
    methods: ['post'],
    url: 'http://localhost/orders/{diningSession}/send-kitchen',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::sendToKitchen
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:394
 * @route "http://localhost/orders/{diningSession}/send-kitchen"
 */
sendKitchen.url = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { diningSession: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { diningSession: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            diningSession: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        diningSession:
            typeof args.diningSession === 'object'
                ? args.diningSession.id
                : args.diningSession,
    };

    return (
        sendKitchen.definition.url
            .replace('{diningSession}', parsedArgs.diningSession.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::sendToKitchen
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:394
 * @route "http://localhost/orders/{diningSession}/send-kitchen"
 */
sendKitchen.post = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: sendKitchen.url(args, options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::sendToKitchen
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:394
 * @route "http://localhost/orders/{diningSession}/send-kitchen"
 */
const sendKitchenForm = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: sendKitchen.url(args, options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::sendToKitchen
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:394
 * @route "http://localhost/orders/{diningSession}/send-kitchen"
 */
sendKitchenForm.post = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: sendKitchen.url(args, options),
    method: 'post',
});

sendKitchen.form = sendKitchenForm;
/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::settle
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:753
 * @route "http://localhost/orders/{diningSession}/settle"
 */
export const settle = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: settle.url(args, options),
    method: 'post',
});

settle.definition = {
    methods: ['post'],
    url: 'http://localhost/orders/{diningSession}/settle',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::settle
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:753
 * @route "http://localhost/orders/{diningSession}/settle"
 */
settle.url = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { diningSession: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { diningSession: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            diningSession: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        diningSession:
            typeof args.diningSession === 'object'
                ? args.diningSession.id
                : args.diningSession,
    };

    return (
        settle.definition.url
            .replace('{diningSession}', parsedArgs.diningSession.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::settle
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:753
 * @route "http://localhost/orders/{diningSession}/settle"
 */
settle.post = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: settle.url(args, options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::settle
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:753
 * @route "http://localhost/orders/{diningSession}/settle"
 */
const settleForm = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: settle.url(args, options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::settle
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:753
 * @route "http://localhost/orders/{diningSession}/settle"
 */
settleForm.post = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: settle.url(args, options),
    method: 'post',
});

settle.form = settleForm;
/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::closeOrder
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:1045
 * @route "http://localhost/orders/{diningSession}/close"
 */
export const close = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: close.url(args, options),
    method: 'post',
});

close.definition = {
    methods: ['post'],
    url: 'http://localhost/orders/{diningSession}/close',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::closeOrder
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:1045
 * @route "http://localhost/orders/{diningSession}/close"
 */
close.url = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { diningSession: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { diningSession: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            diningSession: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        diningSession:
            typeof args.diningSession === 'object'
                ? args.diningSession.id
                : args.diningSession,
    };

    return (
        close.definition.url
            .replace('{diningSession}', parsedArgs.diningSession.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::closeOrder
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:1045
 * @route "http://localhost/orders/{diningSession}/close"
 */
close.post = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: close.url(args, options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::closeOrder
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:1045
 * @route "http://localhost/orders/{diningSession}/close"
 */
const closeForm = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: close.url(args, options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::closeOrder
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:1045
 * @route "http://localhost/orders/{diningSession}/close"
 */
closeForm.post = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: close.url(args, options),
    method: 'post',
});

close.form = closeForm;

const orders = {
    show,
    'send-kitchen': sendKitchen,
    settle,
    close,
    manage: Object.assign(manage, manageF1b31d3),
    items,
    printJobs,
    printLines,
    currentInvoice,
    invoices,
    customer,
};

export default orders;
