// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpExceptions
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:10
 * @route "http://localhost:8000/features/errors/http-exceptions"
 */
export const httpExceptions = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: httpExceptions.url(options),
    method: "get",
})

httpExceptions.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/features/errors/http-exceptions",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpExceptions
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:10
 * @route "http://localhost:8000/features/errors/http-exceptions"
 */
httpExceptions.url = (options?: RouteQueryOptions) => {
    return httpExceptions.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpExceptions
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:10
 * @route "http://localhost:8000/features/errors/http-exceptions"
 */
httpExceptions.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: httpExceptions.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpExceptions
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:10
 * @route "http://localhost:8000/features/errors/http-exceptions"
 */
httpExceptions.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: httpExceptions.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpExceptions
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:10
 * @route "http://localhost:8000/features/errors/http-exceptions"
 */
const httpExceptionsForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpExceptions.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpExceptions
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:10
 * @route "http://localhost:8000/features/errors/http-exceptions"
 */
httpExceptionsForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpExceptions.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpExceptions
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:10
 * @route "http://localhost:8000/features/errors/http-exceptions"
 */
httpExceptionsForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpExceptions.url(formSafeOptions("head", options)),
    method: "get",
})



httpExceptions.form = httpExceptionsForm
/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException403
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:15
 * @route "http://localhost:8000/features/errors/http-exceptions/403"
 */
export const httpException403 = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: httpException403.url(options),
    method: "get",
})

httpException403.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/features/errors/http-exceptions/403",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException403
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:15
 * @route "http://localhost:8000/features/errors/http-exceptions/403"
 */
httpException403.url = (options?: RouteQueryOptions) => {
    return httpException403.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException403
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:15
 * @route "http://localhost:8000/features/errors/http-exceptions/403"
 */
httpException403.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: httpException403.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException403
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:15
 * @route "http://localhost:8000/features/errors/http-exceptions/403"
 */
httpException403.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: httpException403.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException403
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:15
 * @route "http://localhost:8000/features/errors/http-exceptions/403"
 */
const httpException403Form = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpException403.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException403
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:15
 * @route "http://localhost:8000/features/errors/http-exceptions/403"
 */
httpException403Form.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpException403.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException403
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:15
 * @route "http://localhost:8000/features/errors/http-exceptions/403"
 */
httpException403Form.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpException403.url(formSafeOptions("head", options)),
    method: "get",
})



httpException403.form = httpException403Form
/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException404
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:20
 * @route "http://localhost:8000/features/errors/http-exceptions/404"
 */
export const httpException404 = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: httpException404.url(options),
    method: "get",
})

httpException404.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/features/errors/http-exceptions/404",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException404
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:20
 * @route "http://localhost:8000/features/errors/http-exceptions/404"
 */
httpException404.url = (options?: RouteQueryOptions) => {
    return httpException404.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException404
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:20
 * @route "http://localhost:8000/features/errors/http-exceptions/404"
 */
httpException404.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: httpException404.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException404
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:20
 * @route "http://localhost:8000/features/errors/http-exceptions/404"
 */
httpException404.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: httpException404.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException404
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:20
 * @route "http://localhost:8000/features/errors/http-exceptions/404"
 */
const httpException404Form = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpException404.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException404
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:20
 * @route "http://localhost:8000/features/errors/http-exceptions/404"
 */
httpException404Form.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpException404.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException404
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:20
 * @route "http://localhost:8000/features/errors/http-exceptions/404"
 */
httpException404Form.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpException404.url(formSafeOptions("head", options)),
    method: "get",
})



httpException404.form = httpException404Form
/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException500
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:25
 * @route "http://localhost:8000/features/errors/http-exceptions/500"
 */
export const httpException500 = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: httpException500.url(options),
    method: "get",
})

httpException500.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/features/errors/http-exceptions/500",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException500
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:25
 * @route "http://localhost:8000/features/errors/http-exceptions/500"
 */
httpException500.url = (options?: RouteQueryOptions) => {
    return httpException500.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException500
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:25
 * @route "http://localhost:8000/features/errors/http-exceptions/500"
 */
httpException500.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: httpException500.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException500
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:25
 * @route "http://localhost:8000/features/errors/http-exceptions/500"
 */
httpException500.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: httpException500.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException500
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:25
 * @route "http://localhost:8000/features/errors/http-exceptions/500"
 */
const httpException500Form = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpException500.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException500
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:25
 * @route "http://localhost:8000/features/errors/http-exceptions/500"
 */
httpException500Form.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpException500.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpException500
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:25
 * @route "http://localhost:8000/features/errors/http-exceptions/500"
 */
httpException500Form.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpException500.url(formSafeOptions("head", options)),
    method: "get",
})



httpException500.form = httpException500Form
/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpExceptionUnhandled
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:30
 * @route "http://localhost:8000/features/errors/http-exceptions/unhandled"
 */
export const httpExceptionUnhandled = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: httpExceptionUnhandled.url(options),
    method: "get",
})

httpExceptionUnhandled.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/features/errors/http-exceptions/unhandled",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpExceptionUnhandled
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:30
 * @route "http://localhost:8000/features/errors/http-exceptions/unhandled"
 */
httpExceptionUnhandled.url = (options?: RouteQueryOptions) => {
    return httpExceptionUnhandled.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpExceptionUnhandled
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:30
 * @route "http://localhost:8000/features/errors/http-exceptions/unhandled"
 */
httpExceptionUnhandled.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: httpExceptionUnhandled.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpExceptionUnhandled
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:30
 * @route "http://localhost:8000/features/errors/http-exceptions/unhandled"
 */
httpExceptionUnhandled.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: httpExceptionUnhandled.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpExceptionUnhandled
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:30
 * @route "http://localhost:8000/features/errors/http-exceptions/unhandled"
 */
const httpExceptionUnhandledForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpExceptionUnhandled.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpExceptionUnhandled
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:30
 * @route "http://localhost:8000/features/errors/http-exceptions/unhandled"
 */
httpExceptionUnhandledForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpExceptionUnhandled.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::httpExceptionUnhandled
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:30
 * @route "http://localhost:8000/features/errors/http-exceptions/unhandled"
 */
httpExceptionUnhandledForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: httpExceptionUnhandled.url(formSafeOptions("head", options)),
    method: "get",
})



httpExceptionUnhandled.form = httpExceptionUnhandledForm
/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::networkErrors
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:35
 * @route "http://localhost:8000/features/errors/network-errors"
 */
export const networkErrors = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: networkErrors.url(options),
    method: "get",
})

networkErrors.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/features/errors/network-errors",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::networkErrors
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:35
 * @route "http://localhost:8000/features/errors/network-errors"
 */
networkErrors.url = (options?: RouteQueryOptions) => {
    return networkErrors.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::networkErrors
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:35
 * @route "http://localhost:8000/features/errors/network-errors"
 */
networkErrors.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: networkErrors.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::networkErrors
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:35
 * @route "http://localhost:8000/features/errors/network-errors"
 */
networkErrors.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: networkErrors.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::networkErrors
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:35
 * @route "http://localhost:8000/features/errors/network-errors"
 */
const networkErrorsForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: networkErrors.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::networkErrors
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:35
 * @route "http://localhost:8000/features/errors/network-errors"
 */
networkErrorsForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: networkErrors.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Feature\NetworkErrorController::networkErrors
 * @see \D:\Lar\dmpos\app\Http\Controllers\Feature\NetworkErrorController.php:35
 * @route "http://localhost:8000/features/errors/network-errors"
 */
networkErrorsForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: networkErrors.url(formSafeOptions("head", options)),
    method: "get",
})



networkErrors.form = networkErrorsForm

const NetworkErrorController = {
    httpExceptions,
    httpException403,
    httpException404,
    httpException500,
    httpExceptionUnhandled,
    networkErrors,
}

export default NetworkErrorController