// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    applyUrlDefaults,
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../index';

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:30
 * @route "http://localhost/stock-movements/write-off/create"
 */
export const create = (
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: create.url(options),
    method: 'get',
});

create.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/stock-movements/write-off/create',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:30
 * @route "http://localhost/stock-movements/write-off/create"
 */
create.url = (options?: RouteQueryOptions) => {
    return create.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:30
 * @route "http://localhost/stock-movements/write-off/create"
 */
create.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: create.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:30
 * @route "http://localhost/stock-movements/write-off/create"
 */
create.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: create.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:30
 * @route "http://localhost/stock-movements/write-off/create"
 */
const createForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: create.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:30
 * @route "http://localhost/stock-movements/write-off/create"
 */
createForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: create.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::create
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:30
 * @route "http://localhost/stock-movements/write-off/create"
 */
createForm.head = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: create.url(formSafeOptions('head', options)),
    method: 'get',
});

create.form = createForm;
/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:194
 * @route "http://localhost/stock-movements/write-off"
 */
export const store = (
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: store.url(options),
    method: 'post',
});

store.definition = {
    methods: ['post'],
    url: 'http://localhost/stock-movements/write-off',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:194
 * @route "http://localhost/stock-movements/write-off"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:194
 * @route "http://localhost/stock-movements/write-off"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<'post'> => ({
    url: store.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:194
 * @route "http://localhost/stock-movements/write-off"
 */
const storeForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::store
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:194
 * @route "http://localhost/stock-movements/write-off"
 */
storeForm.post = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(options),
    method: 'post',
});

store.form = storeForm;
/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:292
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/approve"
 */
export const approve = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: approve.url(args, options),
    method: 'patch',
});

approve.definition = {
    methods: ['patch'],
    url: 'http://localhost/stock-movements/write-off/{stockAdjustment}/approve',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:292
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/approve"
 */
approve.url = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { stockAdjustment: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { stockAdjustment: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            stockAdjustment: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        stockAdjustment:
            typeof args.stockAdjustment === 'object'
                ? args.stockAdjustment.id
                : args.stockAdjustment,
    };

    return (
        approve.definition.url
            .replace('{stockAdjustment}', parsedArgs.stockAdjustment.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:292
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/approve"
 */
approve.patch = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: approve.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:292
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/approve"
 */
const approveForm = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: approve.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::approve
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:292
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/approve"
 */
approveForm.patch = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: approve.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

approve.form = approveForm;
/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:375
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/reject"
 */
export const reject = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: reject.url(args, options),
    method: 'patch',
});

reject.definition = {
    methods: ['patch'],
    url: 'http://localhost/stock-movements/write-off/{stockAdjustment}/reject',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:375
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/reject"
 */
reject.url = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { stockAdjustment: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { stockAdjustment: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            stockAdjustment: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        stockAdjustment:
            typeof args.stockAdjustment === 'object'
                ? args.stockAdjustment.id
                : args.stockAdjustment,
    };

    return (
        reject.definition.url
            .replace('{stockAdjustment}', parsedArgs.stockAdjustment.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:375
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/reject"
 */
reject.patch = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: reject.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:375
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/reject"
 */
const rejectForm = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: reject.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::reject
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:375
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/reject"
 */
rejectForm.patch = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: reject.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

reject.form = rejectForm;
/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:389
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/cancel"
 */
export const cancel = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: cancel.url(args, options),
    method: 'patch',
});

cancel.definition = {
    methods: ['patch'],
    url: 'http://localhost/stock-movements/write-off/{stockAdjustment}/cancel',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:389
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/cancel"
 */
cancel.url = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { stockAdjustment: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { stockAdjustment: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            stockAdjustment: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        stockAdjustment:
            typeof args.stockAdjustment === 'object'
                ? args.stockAdjustment.id
                : args.stockAdjustment,
    };

    return (
        cancel.definition.url
            .replace('{stockAdjustment}', parsedArgs.stockAdjustment.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:389
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/cancel"
 */
cancel.patch = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: cancel.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:389
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/cancel"
 */
const cancelForm = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: cancel.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\StockMovements\StockWriteOffController::cancel
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/StockMovements/StockWriteOffController.php:389
 * @route "http://localhost/stock-movements/write-off/{stockAdjustment}/cancel"
 */
cancelForm.patch = (
    args:
        | { stockAdjustment: number | { id: number } }
        | [stockAdjustment: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: cancel.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

cancel.form = cancelForm;

const writeOff = {
    create,
    store,
    approve,
    reject,
    cancel,
};

export default writeOff;
