// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import AccessControl from './AccessControl';
import BalanceOnHand from './BalanceOnHand';
import Crm from './Crm';
import Feature from './Feature';
import GoodsReceipt from './GoodsReceipt';
import MasterData from './MasterData';
import MembershipCard from './MembershipCard';
import OperationsReport from './OperationsReport';
import POS from './POS';
import ProfilePictureController from './ProfilePictureController';
import Purchase from './Purchase';
import Putaway from './Putaway';
import Sales from './Sales';
import Seats from './Seats';
import StockCustomer from './StockCustomer';
import StockMovements from './StockMovements';
import Users from './Users';

export const Controllers = {
    ProfilePictureController,
    Purchase,
    StockCustomer,
    AccessControl,
    BalanceOnHand,
    MembershipCard,
    OperationsReport,
    Putaway,
    Crm,
    Users,
    Sales,
    POS,
    Seats,
    Feature,
    GoodsReceipt,
    MasterData,
    StockMovements,
};

export default Controllers;
