// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import BalanceOnHand from './BalanceOnHand';
import Crm from './Crm';
import Feature from './Feature';
import GoodsReceipt from './GoodsReceipt';
import MasterData from './MasterData';
import POS from './POS';
import ProfilePictureController from './ProfilePictureController';
import Purchase from './Purchase';
import Putaway from './Putaway';
import Sales from './Sales';
import Seats from './Seats';
import StockMovements from './StockMovements';

export const Controllers = {
    ProfilePictureController,
    MasterData,
    StockMovements,
    Crm,
    Putaway,
    GoodsReceipt,
    POS,
    Sales,
    BalanceOnHand,
    Purchase,
    Feature,
    Seats,
};

export default Controllers;
