// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\ProfilePictureController::update
 * @see \D:\Lar\dmpos\app\Http\Controllers\ProfilePictureController.php:11
 * @route "http://localhost:8000/profile/picture"
 */
export const update = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: update.url(options),
    method: "post",
})

update.definition = {
    methods: ["post"],
    url: "http://localhost:8000/profile/picture",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\ProfilePictureController::update
 * @see \D:\Lar\dmpos\app\Http\Controllers\ProfilePictureController.php:11
 * @route "http://localhost:8000/profile/picture"
 */
update.url = (options?: RouteQueryOptions) => {
    return update.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProfilePictureController::update
 * @see \D:\Lar\dmpos\app\Http\Controllers\ProfilePictureController.php:11
 * @route "http://localhost:8000/profile/picture"
 */
update.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: update.url(options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\ProfilePictureController::update
 * @see \D:\Lar\dmpos\app\Http\Controllers\ProfilePictureController.php:11
 * @route "http://localhost:8000/profile/picture"
 */
const updateForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: update.url(options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\ProfilePictureController::update
 * @see \D:\Lar\dmpos\app\Http\Controllers\ProfilePictureController.php:11
 * @route "http://localhost:8000/profile/picture"
 */
updateForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: update.url(options),
    method: "post",
})



update.form = updateForm

const ProfilePictureController = {
    update,
}

export default ProfilePictureController