// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import categories from "./categories";
import menus from "./menus";
import prices from "./prices";

export const menu = {
    categories,
    menus,
    prices,
}

export default menu