// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    applyUrlDefaults,
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../../index';

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::updateCustomer
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:927
 * @route "http://localhost/orders/{diningSession}/customer"
 */
export const update = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: update.url(args, options),
    method: 'patch',
});

update.definition = {
    methods: ['patch'],
    url: 'http://localhost/orders/{diningSession}/customer',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::updateCustomer
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:927
 * @route "http://localhost/orders/{diningSession}/customer"
 */
update.url = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { diningSession: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { diningSession: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            diningSession: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        diningSession:
            typeof args.diningSession === 'object'
                ? args.diningSession.id
                : args.diningSession,
    };

    return (
        update.definition.url
            .replace('{diningSession}', parsedArgs.diningSession.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::updateCustomer
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:927
 * @route "http://localhost/orders/{diningSession}/customer"
 */
update.patch = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: update.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::updateCustomer
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:927
 * @route "http://localhost/orders/{diningSession}/customer"
 */
const updateForm = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: update.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::updateCustomer
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Seats/SeatOrderController.php:927
 * @route "http://localhost/orders/{diningSession}/customer"
 */
updateForm.patch = (
    args:
        | { diningSession: number | { id: number } }
        | [diningSession: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: update.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

update.form = updateForm;

const customer = {
    update,
};

export default customer;
