// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::previewInvoiceDocument
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:566
 * @route "http://localhost:8000/orders/{diningSession}/invoices/{invoice}/print/{documentType}"
 */
export const preview = (args: { diningSession: number | { id: number }, invoice: number | { id: number }, documentType: string | number } | [ diningSession: number | { id: number }, invoice: number | { id: number }, documentType: string | number ], options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: preview.url(args, options),
    method: "get",
})

preview.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/orders/{diningSession}/invoices/{invoice}/print/{documentType}",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::previewInvoiceDocument
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:566
 * @route "http://localhost:8000/orders/{diningSession}/invoices/{invoice}/print/{documentType}"
 */
preview.url = (args: { diningSession: number | { id: number }, invoice: number | { id: number }, documentType: string | number } | [ diningSession: number | { id: number }, invoice: number | { id: number }, documentType: string | number ], options?: RouteQueryOptions) => {
    if (Array.isArray(args)) {
    args = {
        diningSession: args[0],
        invoice: args[1],
        documentType: args[2],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        diningSession: typeof args.diningSession === "object" ? args.diningSession.id : args.diningSession,
        invoice: typeof args.invoice === "object" ? args.invoice.id : args.invoice,
        documentType: args.documentType,
    }
    
    return preview.definition.url
        .replace("{diningSession}", parsedArgs.diningSession.toString())
        .replace("{invoice}", parsedArgs.invoice.toString())
        .replace("{documentType}", parsedArgs.documentType.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::previewInvoiceDocument
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:566
 * @route "http://localhost:8000/orders/{diningSession}/invoices/{invoice}/print/{documentType}"
 */
preview.get = (args: { diningSession: number | { id: number }, invoice: number | { id: number }, documentType: string | number } | [ diningSession: number | { id: number }, invoice: number | { id: number }, documentType: string | number ], options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: preview.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::previewInvoiceDocument
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:566
 * @route "http://localhost:8000/orders/{diningSession}/invoices/{invoice}/print/{documentType}"
 */
preview.head = (args: { diningSession: number | { id: number }, invoice: number | { id: number }, documentType: string | number } | [ diningSession: number | { id: number }, invoice: number | { id: number }, documentType: string | number ], options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: preview.url(args, options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::previewInvoiceDocument
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:566
 * @route "http://localhost:8000/orders/{diningSession}/invoices/{invoice}/print/{documentType}"
 */
const previewForm = (args: { diningSession: number | { id: number }, invoice: number | { id: number }, documentType: string | number } | [ diningSession: number | { id: number }, invoice: number | { id: number }, documentType: string | number ], options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: preview.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::previewInvoiceDocument
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:566
 * @route "http://localhost:8000/orders/{diningSession}/invoices/{invoice}/print/{documentType}"
 */
previewForm.get = (args: { diningSession: number | { id: number }, invoice: number | { id: number }, documentType: string | number } | [ diningSession: number | { id: number }, invoice: number | { id: number }, documentType: string | number ], options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: preview.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Seats\SeatOrderController::previewInvoiceDocument
 * @see \D:\Lar\dmpos\app\Http\Controllers\Seats\SeatOrderController.php:566
 * @route "http://localhost:8000/orders/{diningSession}/invoices/{invoice}/print/{documentType}"
 */
previewForm.head = (args: { diningSession: number | { id: number }, invoice: number | { id: number }, documentType: string | number } | [ diningSession: number | { id: number }, invoice: number | { id: number }, documentType: string | number ], options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: preview.url(args, formSafeOptions("head", options)),
    method: "get",
})



preview.form = previewForm

const invoices = {
    preview,
}

export default invoices