// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:19
 * @route "http://localhost:8000/sales"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "http://localhost:8000/sales",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:19
 * @route "http://localhost:8000/sales"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:19
 * @route "http://localhost:8000/sales"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:19
 * @route "http://localhost:8000/sales"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:19
 * @route "http://localhost:8000/sales"
 */
const indexForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:19
 * @route "http://localhost:8000/sales"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::index
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:19
 * @route "http://localhost:8000/sales"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(formSafeOptions("head", options)),
    method: "get",
})



index.form = indexForm
/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::receive
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:84
 * @route "http://localhost:8000/sales/invoices/{invoice}/receive"
 */
export const receive = (args: { invoice: number | { id: number } } | [ invoice: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: receive.url(args, options),
    method: "post",
})

receive.definition = {
    methods: ["post"],
    url: "http://localhost:8000/sales/invoices/{invoice}/receive",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::receive
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:84
 * @route "http://localhost:8000/sales/invoices/{invoice}/receive"
 */
receive.url = (args: { invoice: number | { id: number } } | [ invoice: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { invoice: args }
}
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
    args = { invoice: args.id }
}
    
    if (Array.isArray(args)) {
    args = {
        invoice: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        invoice: typeof args.invoice === "object" ? args.invoice.id : args.invoice,
    }
    
    return receive.definition.url
        .replace("{invoice}", parsedArgs.invoice.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::receive
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:84
 * @route "http://localhost:8000/sales/invoices/{invoice}/receive"
 */
receive.post = (args: { invoice: number | { id: number } } | [ invoice: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: receive.url(args, options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::receive
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:84
 * @route "http://localhost:8000/sales/invoices/{invoice}/receive"
 */
const receiveForm = (args: { invoice: number | { id: number } } | [ invoice: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: receive.url(args, options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\Sales\SaleInvoiceController::receive
 * @see \D:\Lar\dmpos\app\Http\Controllers\Sales\SaleInvoiceController.php:84
 * @route "http://localhost:8000/sales/invoices/{invoice}/receive"
 */
receiveForm.post = (args: { invoice: number | { id: number } } | [ invoice: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: receive.url(args, options),
    method: "post",
})



receive.form = receiveForm

const SaleInvoiceController = {
    index,
    receive,
}

export default SaleInvoiceController