// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \App\Http\Controllers\OperationsReport\DailySessionMenuController::__invoke
 * @see \D:\Lar\dmpos\app\Http\Controllers\OperationsReport\DailySessionMenuController.php:18
 * @route "http://127.0.0.1:8000/operations-report/daily-session-menu"
 */
const DailySessionMenuController = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: DailySessionMenuController.url(options),
    method: "get",
})

DailySessionMenuController.definition = {
    methods: ["get","head"],
    url: "http://127.0.0.1:8000/operations-report/daily-session-menu",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\OperationsReport\DailySessionMenuController::__invoke
 * @see \D:\Lar\dmpos\app\Http\Controllers\OperationsReport\DailySessionMenuController.php:18
 * @route "http://127.0.0.1:8000/operations-report/daily-session-menu"
 */
DailySessionMenuController.url = (options?: RouteQueryOptions) => {
    return DailySessionMenuController.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\OperationsReport\DailySessionMenuController::__invoke
 * @see \D:\Lar\dmpos\app\Http\Controllers\OperationsReport\DailySessionMenuController.php:18
 * @route "http://127.0.0.1:8000/operations-report/daily-session-menu"
 */
DailySessionMenuController.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: DailySessionMenuController.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\OperationsReport\DailySessionMenuController::__invoke
 * @see \D:\Lar\dmpos\app\Http\Controllers\OperationsReport\DailySessionMenuController.php:18
 * @route "http://127.0.0.1:8000/operations-report/daily-session-menu"
 */
DailySessionMenuController.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: DailySessionMenuController.url(options),
    method: "head",
})



/**
 * @see \App\Http\Controllers\OperationsReport\DailySessionMenuController::__invoke
 * @see \D:\Lar\dmpos\app\Http\Controllers\OperationsReport\DailySessionMenuController.php:18
 * @route "http://127.0.0.1:8000/operations-report/daily-session-menu"
 */
const DailySessionMenuControllerForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: DailySessionMenuController.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\OperationsReport\DailySessionMenuController::__invoke
 * @see \D:\Lar\dmpos\app\Http\Controllers\OperationsReport\DailySessionMenuController.php:18
 * @route "http://127.0.0.1:8000/operations-report/daily-session-menu"
 */
DailySessionMenuControllerForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: DailySessionMenuController.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\OperationsReport\DailySessionMenuController::__invoke
 * @see \D:\Lar\dmpos\app\Http\Controllers\OperationsReport\DailySessionMenuController.php:18
 * @route "http://127.0.0.1:8000/operations-report/daily-session-menu"
 */
DailySessionMenuControllerForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: DailySessionMenuController.url(formSafeOptions("head", options)),
    method: "get",
})



DailySessionMenuController.form = DailySessionMenuControllerForm

export default DailySessionMenuController