// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import DailySessionMenuController from "./DailySessionMenuController";
import DailySessionStockController from "./DailySessionStockController";

export const OperationsReport = {
    DailySessionMenuController,
    DailySessionStockController,
}

export default OperationsReport