// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../../index';

/**
 * @see \App\Http\Controllers\Feature\EventController::visitCallbacksAction
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:27
 * @route "http://localhost/features/events/visit-callbacks/action"
 */
export const action = (
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: action.url(options),
    method: 'post',
});

action.definition = {
    methods: ['post'],
    url: 'http://localhost/features/events/visit-callbacks/action',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\Feature\EventController::visitCallbacksAction
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:27
 * @route "http://localhost/features/events/visit-callbacks/action"
 */
action.url = (options?: RouteQueryOptions) => {
    return action.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\Feature\EventController::visitCallbacksAction
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:27
 * @route "http://localhost/features/events/visit-callbacks/action"
 */
action.post = (options?: RouteQueryOptions): RouteDefinition<'post'> => ({
    url: action.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Feature\EventController::visitCallbacksAction
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:27
 * @route "http://localhost/features/events/visit-callbacks/action"
 */
const actionForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: action.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\Feature\EventController::visitCallbacksAction
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/Feature/EventController.php:27
 * @route "http://localhost/features/events/visit-callbacks/action"
 */
actionForm.post = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: action.url(options),
    method: 'post',
});

action.form = actionForm;

const visitCallbacks = {
    action,
};

export default visitCallbacks;
