// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemServiceProvider.php:106
 * @route "http://localhost:8000/storage/{path}"
 */
export const upload = (args: { path: string | number } | [ path: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: upload.url(args, options),
    method: "put",
})

upload.definition = {
    methods: ["put"],
    url: "http://localhost:8000/storage/{path}",
} satisfies RouteDefinition<["put"]>

/**
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemServiceProvider.php:106
 * @route "http://localhost:8000/storage/{path}"
 */
upload.url = (args: { path: string | number } | [ path: string | number ] | string | number, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
    args = { path: args }
}
    
    if (Array.isArray(args)) {
    args = {
        path: args[0],
    }
}
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        path: args.path,
    }
    
    return upload.definition.url
        .replace("{path}", parsedArgs.path.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemServiceProvider.php:106
 * @route "http://localhost:8000/storage/{path}"
 */
upload.put = (args: { path: string | number } | [ path: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: upload.url(args, options),
    method: "put",
})



/**
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemServiceProvider.php:106
 * @route "http://localhost:8000/storage/{path}"
 */
const uploadForm = (args: { path: string | number } | [ path: string | number ] | string | number, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: upload.url(args, formSafeOptions("put", options)),
    method: "post",
})

/**
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemServiceProvider.php:106
 * @route "http://localhost:8000/storage/{path}"
 */
uploadForm.put = (args: { path: string | number } | [ path: string | number ] | string | number, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: upload.url(args, formSafeOptions("put", options)),
    method: "post",
})



upload.form = uploadForm

const local = {
    upload,
}

export default local