// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
const RedirectController = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: RedirectController.url(options),
    method: "get",
})

RedirectController.definition = {
    methods: ["get","head","post","put","patch","delete","options"],
    url: "http://localhost:8000",
} satisfies RouteDefinition<["get","head","post","put","patch","delete","options"]>

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectController.url = (options?: RouteQueryOptions) => {
    return RedirectController.definition.url + queryParams(options)
}

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectController.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: RedirectController.url(options),
    method: "get",
})

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectController.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: RedirectController.url(options),
    method: "head",
})

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectController.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: RedirectController.url(options),
    method: "post",
})

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectController.put = (options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: RedirectController.url(options),
    method: "put",
})

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectController.patch = (options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: RedirectController.url(options),
    method: "patch",
})

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectController.delete = (options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: RedirectController.url(options),
    method: "delete",
})

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectController.options = (options?: RouteQueryOptions): RouteDefinition<"options"> => ({
    url: RedirectController.url(options),
    method: "options",
})



/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
const RedirectControllerForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: RedirectController.url(options),
    method: "get",
})

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectControllerForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: RedirectController.url(options),
    method: "get",
})

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectControllerForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: RedirectController.url(formSafeOptions("head", options)),
    method: "get",
})

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectControllerForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: RedirectController.url(options),
    method: "post",
})

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectControllerForm.put = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: RedirectController.url(formSafeOptions("put", options)),
    method: "post",
})

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectControllerForm.patch = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: RedirectController.url(formSafeOptions("patch", options)),
    method: "post",
})

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectControllerForm.delete = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: RedirectController.url(formSafeOptions("delete", options)),
    method: "post",
})

/**
 * @see \Illuminate\Routing\RedirectController::__invoke
 * @see \D:\Lar\dmpos\vendor\laravel\framework\src\Illuminate\Routing\RedirectController.php:19
 * @route "http://localhost:8000"
 */
RedirectControllerForm.options = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: RedirectController.url(formSafeOptions("options", options)),
    method: "get",
})



RedirectController.form = RedirectControllerForm

export default RedirectController