// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    applyUrlDefaults,
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../../../index';

/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:91
 * @route "http://localhost/master-data/products/items"
 */
export const store = (
    options?: RouteQueryOptions,
): RouteDefinition<'post'> => ({
    url: store.url(options),
    method: 'post',
});

store.definition = {
    methods: ['post'],
    url: 'http://localhost/master-data/products/items',
} satisfies RouteDefinition<['post']>;

/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:91
 * @route "http://localhost/master-data/products/items"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:91
 * @route "http://localhost/master-data/products/items"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<'post'> => ({
    url: store.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:91
 * @route "http://localhost/master-data/products/items"
 */
const storeForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(options),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\ProductController::storeItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:91
 * @route "http://localhost/master-data/products/items"
 */
storeForm.post = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: store.url(options),
    method: 'post',
});

store.form = storeForm;
/**
 * @see \App\Http\Controllers\MasterData\ProductController::updateItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:130
 * @route "http://localhost/master-data/products/items/{item}"
 */
export const update = (
    args:
        | { item: number | { id: number } }
        | [item: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: update.url(args, options),
    method: 'patch',
});

update.definition = {
    methods: ['patch'],
    url: 'http://localhost/master-data/products/items/{item}',
} satisfies RouteDefinition<['patch']>;

/**
 * @see \App\Http\Controllers\MasterData\ProductController::updateItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:130
 * @route "http://localhost/master-data/products/items/{item}"
 */
update.url = (
    args:
        | { item: number | { id: number } }
        | [item: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { item: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { item: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            item: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        item: typeof args.item === 'object' ? args.item.id : args.item,
    };

    return (
        update.definition.url
            .replace('{item}', parsedArgs.item.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\MasterData\ProductController::updateItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:130
 * @route "http://localhost/master-data/products/items/{item}"
 */
update.patch = (
    args:
        | { item: number | { id: number } }
        | [item: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'patch'> => ({
    url: update.url(args, options),
    method: 'patch',
});

/**
 * @see \App\Http\Controllers\MasterData\ProductController::updateItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:130
 * @route "http://localhost/master-data/products/items/{item}"
 */
const updateForm = (
    args:
        | { item: number | { id: number } }
        | [item: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: update.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

/**
 * @see \App\Http\Controllers\MasterData\ProductController::updateItem
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/MasterData/ProductController.php:130
 * @route "http://localhost/master-data/products/items/{item}"
 */
updateForm.patch = (
    args:
        | { item: number | { id: number } }
        | [item: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'post'> => ({
    action: update.url(args, formSafeOptions('patch', options)),
    method: 'post',
});

update.form = updateForm;

const items = {
    store,
    update,
};

export default items;
