// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import {
    applyUrlDefaults,
    formSafeOptions,
    queryParams,
    type RouteDefinition,
    type RouteFormDefinition,
    type RouteQueryOptions,
} from './../../index';

/**
 * @see \App\Http\Controllers\BalanceOnHand\BalanceOnHandController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/BalanceOnHand/BalanceOnHandController.php:16
 * @route "http://localhost/balance-on-hand"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

index.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/balance-on-hand',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\BalanceOnHand\BalanceOnHandController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/BalanceOnHand/BalanceOnHandController.php:16
 * @route "http://localhost/balance-on-hand"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options);
};

/**
 * @see \App\Http\Controllers\BalanceOnHand\BalanceOnHandController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/BalanceOnHand/BalanceOnHandController.php:16
 * @route "http://localhost/balance-on-hand"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<'get'> => ({
    url: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\BalanceOnHand\BalanceOnHandController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/BalanceOnHand/BalanceOnHandController.php:16
 * @route "http://localhost/balance-on-hand"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<'head'> => ({
    url: index.url(options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\BalanceOnHand\BalanceOnHandController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/BalanceOnHand/BalanceOnHandController.php:16
 * @route "http://localhost/balance-on-hand"
 */
const indexForm = (
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\BalanceOnHand\BalanceOnHandController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/BalanceOnHand/BalanceOnHandController.php:16
 * @route "http://localhost/balance-on-hand"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\BalanceOnHand\BalanceOnHandController::index
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/BalanceOnHand/BalanceOnHandController.php:16
 * @route "http://localhost/balance-on-hand"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<'get'> => ({
    action: index.url(formSafeOptions('head', options)),
    method: 'get',
});

index.form = indexForm;
/**
 * @see \App\Http\Controllers\BalanceOnHand\BalanceOnHandController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/BalanceOnHand/BalanceOnHandController.php:65
 * @route "http://localhost/balance-on-hand/{item}"
 */
export const show = (
    args:
        | { item: number | { id: number } }
        | [item: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: show.url(args, options),
    method: 'get',
});

show.definition = {
    methods: ['get', 'head'],
    url: 'http://localhost/balance-on-hand/{item}',
} satisfies RouteDefinition<['get', 'head']>;

/**
 * @see \App\Http\Controllers\BalanceOnHand\BalanceOnHandController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/BalanceOnHand/BalanceOnHandController.php:65
 * @route "http://localhost/balance-on-hand/{item}"
 */
show.url = (
    args:
        | { item: number | { id: number } }
        | [item: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
) => {
    if (typeof args === 'string' || typeof args === 'number') {
        args = { item: args };
    }

    if (typeof args === 'object' && !Array.isArray(args) && 'id' in args) {
        args = { item: args.id };
    }

    if (Array.isArray(args)) {
        args = {
            item: args[0],
        };
    }

    args = applyUrlDefaults(args);

    const parsedArgs = {
        item: typeof args.item === 'object' ? args.item.id : args.item,
    };

    return (
        show.definition.url
            .replace('{item}', parsedArgs.item.toString())
            .replace(/\/+$/, '') + queryParams(options)
    );
};

/**
 * @see \App\Http\Controllers\BalanceOnHand\BalanceOnHandController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/BalanceOnHand/BalanceOnHandController.php:65
 * @route "http://localhost/balance-on-hand/{item}"
 */
show.get = (
    args:
        | { item: number | { id: number } }
        | [item: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'get'> => ({
    url: show.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\BalanceOnHand\BalanceOnHandController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/BalanceOnHand/BalanceOnHandController.php:65
 * @route "http://localhost/balance-on-hand/{item}"
 */
show.head = (
    args:
        | { item: number | { id: number } }
        | [item: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteDefinition<'head'> => ({
    url: show.url(args, options),
    method: 'head',
});

/**
 * @see \App\Http\Controllers\BalanceOnHand\BalanceOnHandController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/BalanceOnHand/BalanceOnHandController.php:65
 * @route "http://localhost/balance-on-hand/{item}"
 */
const showForm = (
    args:
        | { item: number | { id: number } }
        | [item: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: show.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\BalanceOnHand\BalanceOnHandController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/BalanceOnHand/BalanceOnHandController.php:65
 * @route "http://localhost/balance-on-hand/{item}"
 */
showForm.get = (
    args:
        | { item: number | { id: number } }
        | [item: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: show.url(args, options),
    method: 'get',
});

/**
 * @see \App\Http\Controllers\BalanceOnHand\BalanceOnHandController::show
 * @see /home/runner/work/dmpos/dmpos/app/Http/Controllers/BalanceOnHand/BalanceOnHandController.php:65
 * @route "http://localhost/balance-on-hand/{item}"
 */
showForm.head = (
    args:
        | { item: number | { id: number } }
        | [item: number | { id: number }]
        | number
        | { id: number },
    options?: RouteQueryOptions,
): RouteFormDefinition<'get'> => ({
    action: show.url(args, formSafeOptions('head', options)),
    method: 'get',
});

show.form = showForm;

const balanceOnHand = {
    index,
    show,
};

export default balanceOnHand;
